{{- $ns := include "siros-id.namespace" . -}}
---
{{ include "siros-id.certificate" (list . (dict
   "name" "mongodb-server"
   "literalSubject" (printf "CN=mongodb-svc.%s.svc.%s" $ns .Values.global.clusterDomain)
   "dnsNames" (list (printf "mongodb-svc.%s.svc.%s" $ns .Values.global.clusterDomain) (printf "*.mongodb-svc.%s.svc.%s" $ns .Values.global.clusterDomain) "mongodb-svc")
   "usages" (list "digital signature" "key encipherment"))) }}

---
{{ include "siros-id.certificate" (list . (dict
   "name" "mongodb-agent"
   "literalSubject" "CN=mongodb-agent,C=SE,OU=clients,O=siros-id"
   "dnsNames" (list "automation" "mms-automation-agent")
   "usages" (list "digital signature" "key encipherment" "client auth"))) }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-database
  namespace: {{ $ns }}
  {{- include "siros-id.labels" (list . (dict)) | nindent 2 }}
  {{- include "siros-id.annotations" (list . (dict)) | nindent 2 }}

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mongodb-database
  namespace: {{ $ns }}
  {{- include "siros-id.labels" (list . (dict)) | nindent 2 }}
  {{- include "siros-id.annotations" (list . (dict)) | nindent 2 }}
rules:
  - apiGroups: [""]
    resources: [secrets]
    verbs: [get]
  - apiGroups: [""]
    resources: [pods]
    verbs: [patch, delete, get]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mongodb-database
  namespace: {{ $ns }}
  {{- include "siros-id.labels" (list . (dict)) | nindent 2 }}
  {{- include "siros-id.annotations" (list . (dict)) | nindent 2 }}
subjects:
  - kind: ServiceAccount
    name: mongodb-database
    namespace: {{ $ns }}
roleRef:
  kind: Role
  name: mongodb-database
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongodb-kubernetes-appdb
  namespace: {{ $ns }}
  {{- include "siros-id.labels" (list . (dict)) | nindent 2 }}
  {{- include "siros-id.annotations" (list . (dict)) | nindent 2 }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mongodb-kubernetes-appdb
  namespace: {{ $ns }}
  {{- include "siros-id.labels" (list . (dict)) | nindent 2 }}
  {{- include "siros-id.annotations" (list . (dict)) | nindent 2 }}
rules:
  - apiGroups: [""]
    resources: [secrets]
    verbs: [get]
  - apiGroups: [""]
    resources: [pods]
    verbs: [patch, delete, get]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mongodb-kubernetes-appdb
  namespace: {{ $ns }}
  {{- include "siros-id.labels" (list . (dict)) | nindent 2 }}
  {{- include "siros-id.annotations" (list . (dict)) | nindent 2 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mongodb-kubernetes-appdb
subjects:
  - kind: ServiceAccount
    name: mongodb-kubernetes-appdb
    namespace: {{ $ns }}

---
apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb
  namespace: {{ $ns }}
  {{- include "siros-id.labels" (list . (dict)) | nindent 2 }}
  {{- include "siros-id.annotations" (list . (dict "mongodb.com/v1.architecture" "static")) | nindent 2 }}
spec:
  type: ReplicaSet
  members: {{ .Values.replicas.mongo }}
  arbiters: 0
  version: {{ .Values.images.mongoCommunityVersion | quote }}
  featureCompatibilityVersion: "7.0"
  clusterDomain: {{ .Values.global.clusterDomain }}
  statefulSet:
    spec:
      template:
        metadata:
          {{- include "siros-id.labels" (list . (dict "app.kubernetes.io/name" "mongodb-svc")) | nindent 10 }}
        spec:
          {{- include "siros-id.topologySpreadConstraints" (list . "mongodb-svc") | nindent 10 }}
          {{- include "siros-id.imagePullSecrets" . | nindent 10 }}
          {{- include "siros-id.podSecurityContext" (dict "runAsUser" 2000) | nindent 10 }}
          initContainers:
            - name: mongodb-agent-readinessprobe
              {{- include "siros-id.imagePullPolicy" . | nindent 14 }}
              {{- include "siros-id.containerSecurityContext" (dict) | nindent 14 }}
              resources:
                {{- toYamlPretty .Values.resources.mongo.mongodbAgentReadinessprobe | nindent 16 }}
            - name: mongod-posthook
              {{- include "siros-id.imagePullPolicy" . | nindent 14 }}
              {{- include "siros-id.containerSecurityContext" (dict) | nindent 14 }}
              resources:
                {{- toYamlPretty .Values.resources.mongo.mongodPosthook | nindent 16 }}
          containers:
            - name: mongod
              {{- include "siros-id.imagePullPolicy" . | nindent 14 }}
              {{- include "siros-id.containerSecurityContext" (dict) | nindent 14 }}
              resources:
                {{- toYamlPretty .Values.resources.mongo.mongod | nindent 16 }}
            - name: mongodb-agent
              {{- include "siros-id.imagePullPolicy" . | nindent 14 }}
              {{- include "siros-id.containerSecurityContext" (dict) | nindent 14 }}
              resources:
                {{- toYamlPretty .Values.resources.mongo.mongodbAgent | nindent 16 }}
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            {{- with .Values.storage.mongo.storageClassName }}
            storageClassName: {{ . | quote }}
            {{- end }}
            resources:
              requests:
                storage: {{ .Values.storage.mongo.data }}
        - metadata:
            name: logs-volume
          spec:
            {{- with .Values.storage.mongo.storageClassName }}
            storageClassName: {{ . | quote }}
            {{- end }}
            resources:
              requests:
                storage: {{ .Values.storage.mongo.logs }}
  security:
    tls:
      enabled: true
      certificateKeySecretRef:
        name: mongodb-server-cert
      caCertificateSecretRef:
        name: mongodb-server-cert
      optional: false
    authentication:
      modes: ["X509"]
      agentMode: "X509"
      agentCertificateSecretRef:
        name: mongodb-agent-cert
  # https://www.mongodb.com/docs/manual/reference/parameters/#mongodb-parameter-param.tlsX509ClusterAuthDNOverride
  # https://www.mongodb.com/docs/manual/core/security-internal-authentication/#x.509
  users:
    - name: "CN=mongodb-admin-client,OU=clients,O=siros-id"
      db: $external
      roles:
        - name: root
          db: admin
        - name: clusterManager
          db: admin
        - name: clusterAdmin
          db: admin
        - name: dbAdminAnyDatabase
          db: admin
        - name: readWriteAnyDatabase
          db: admin
        - name: userAdminAnyDatabase
          db: admin
    - name: "CN=mongo-backup-client,OU=clients,O=siros-id"
      db: $external
      roles:
        - name: backup
          db: admin
        - name: restore
          db: admin
    - name: "CN=wallet-backend-client,OU=clients,O=siros-id"
      db: $external
      roles:
        - name: readWrite
          db: wallet-backend
    - name: "CN=verifier-client,OU=clients,O=siros-id"
      db: $external
      roles:
        - name: readWrite
          db: verifier
        - name: readWrite
          db: verifier_cache
    - name: "CN=issuer-registry-client,OU=clients,O=siros-id"
      db: $external
      roles:
        - name: readWrite
          db: vc_registry
        - name: readWrite
          db: issuer-registry_cache
    - name: "CN=issuer-apigw-client,OU=clients,O=siros-id"
      db: $external
      roles:
        - name: readWrite
          db: vc
        - name: readWrite
          db: issuer-apigw_cache
    {{- if .Values.r2ps.enabled }}
    - name: "CN=r2ps-client,OU=clients,O=siros-id"
      db: $external
      roles:
        - name: readWrite
          db: r2ps
    {{- end }}
  agent:
    logFile: /dev/stdout

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mongodb
  namespace: {{ $ns }}
  {{- include "siros-id.labels" (list . (dict)) | nindent 2 }}
  {{- include "siros-id.annotations" (list . (dict)) | nindent 2 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: mongodb-svc
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: mongodb-svc
    - from:
        - podSelector:
            matchLabels:
              mongodb-access: "true"
      ports:
        - port: 27017
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: mongodb-svc
    # FIXME: How to do we make sure we are using the correct kube-apiserver IP+port?
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              app.kubernetes.io/name: kube-apiserver
      ports:
        - port: {{ .Values.networkPolicies.kubeApiserverPort }}

{{- if .Values.networkPolicies.ciliumNetworkPolicies }}
# NOTE: Cilium does not support NetworkPolicy podSelector for host-networked pods
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: mongodb-kubeapi
  namespace: {{ $ns }}
  {{- include "siros-id.labels" (list . (dict)) | nindent 2 }}
  {{- include "siros-id.annotations" (list . (dict)) | nindent 2 }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: mongodb-svc
  egress:
    - toEntities:
        - kube-apiserver
{{- end }}
