#!/usr/bin/env python3
"""Write the Litestream config for the control plane's SQLite database, from the environment.

    litestream_config.py OUT_PATH        exit 0: written; 10: no replica configured;
                                         2: a replica is half-configured (refuse to guess)

The replica is the S3-compatible bucket that `fly storage create -a <app>` provisions,
read from exactly the names that command sets as app secrets:
  BUCKET_NAME, AWS_ENDPOINT_URL_S3, AWS_REGION, AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY
plus, not secret:
  SIROSID_BACKUP_PATH      key prefix in the bucket (default sirosid.db)
  LITESTREAM_REPLICA_URL   instead of the bucket: any Litestream replica URL. For local
                           testing (file:///dir); an s3:// URL still takes the AWS_* keys.

Credentials NEVER go into the file: it names ${AWS_ACCESS_KEY_ID} and
${AWS_SECRET_ACCESS_KEY}, which Litestream expands from its own environment when it
loads the config. The file on disk can be read by anyone and says nothing secret.

What is replicated is the database file only: plaintext metadata (users, invites'
hashes, instance ids/owners/status/expiry/naming, audit) and SEALED blobs (configs,
specs, instance secrets under each user's passkey-derived key; see
sirosid_service/db.py). Keep it that way: never add a plaintext secret column.
"""
import os
import sys

NOT_CONFIGURED = 10
INCOMPLETE = 2
KEYS = ["      access-key-id: ${AWS_ACCESS_KEY_ID}", "      secret-access-key: ${AWS_SECRET_ACCESS_KEY}"]


def _get(env, name):
    return (env.get(name) or "").strip()


def _q(v: str) -> str:
    """A YAML double-quoted scalar. ${...} is left for Litestream to expand."""
    return '"' + v.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render(env) -> tuple:
    """(exit_code, text_or_message)."""
    db = _get(env, "SIROSID_DB") or "/data/sirosid.db"
    url = _get(env, "LITESTREAM_REPLICA_URL")
    bucket, endpoint, region = _get(env, "BUCKET_NAME"), _get(env, "AWS_ENDPOINT_URL_S3"), _get(env, "AWS_REGION")
    path = _get(env, "SIROSID_BACKUP_PATH") or "sirosid.db"
    has_keys = bool(_get(env, "AWS_ACCESS_KEY_ID")) and bool(_get(env, "AWS_SECRET_ACCESS_KEY"))
    lines = ["# Generated by deploy/control-plane/litestream_config.py - no secrets in here.",
             "dbs:", f"  - path: {_q(db)}", "    replica:"]
    if url:
        lines.append(f"      url: {_q(url)}")
        if url.startswith("s3://"):
            if not has_keys:
                return INCOMPLETE, "LITESTREAM_REPLICA_URL is s3:// but AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY are not both set"
            lines += KEYS
        return 0, "\n".join(lines) + "\n"
    if not (bucket or endpoint):
        return NOT_CONFIGURED, "no replica configured (BUCKET_NAME is not set; `fly storage create -a <app>` sets it)"
    missing = [n for n, v in (("BUCKET_NAME", bucket), ("AWS_ENDPOINT_URL_S3", endpoint)) if not v]
    if not has_keys:
        missing.append("AWS_ACCESS_KEY_ID + AWS_SECRET_ACCESS_KEY")
    if missing:
        return INCOMPLETE, "replica half-configured, missing: " + "; ".join(missing)
    lines += ["      type: s3", f"      bucket: {_q(bucket)}", f"      path: {_q(path)}", f"      endpoint: {_q(endpoint)}",
              f"      region: {_q(region or 'auto')}", *KEYS]
    return 0, "\n".join(lines) + "\n"


def main(argv=None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    if len(argv) != 1:
        print(__doc__.split("\n\n")[0], file=sys.stderr)
        return 1
    code, text = render(os.environ)
    if code != 0:
        print(f"litestream: {text}", file=sys.stderr)
        return code
    fd = os.open(argv[0], os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o644)
    with os.fdopen(fd, "w") as f:
        f.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
