#!/usr/bin/env python3
"""Write the Litestream config for the control plane's SQLite database, from the environment.

    litestream_config.py OUT_PATH        exit 0: written; 10: no replica configured;
                                         2: a replica is half-configured (refuse to guess)

Where the replica is (first match wins):
  LITESTREAM_REPLICA_URL   any Litestream replica URL (s3://bucket/path?endpoint=..., file:///dir)
  LITESTREAM_BUCKET / BUCKET_NAME                     an S3-compatible bucket; with
  LITESTREAM_ENDPOINT / AWS_ENDPOINT_URL_S3           (Tigris: https://fly.storage.tigris.dev)
  LITESTREAM_REGION / AWS_REGION                      (Tigris: auto)
  LITESTREAM_PATH                                     key prefix in the bucket (default sirosid.db)
`fly storage create -a <app>` sets the BUCKET_NAME / AWS_* names as app secrets, so
a Tigris bucket needs no extra configuration.

Credentials NEVER go into the file: it names ${LITESTREAM_ACCESS_KEY_ID} and
${LITESTREAM_SECRET_ACCESS_KEY}, which Litestream expands from its own environment
when it loads the config (the entrypoint copies AWS_* into those names if only they
are set). So the file on disk can be read by anyone and says nothing secret.

What is replicated is the database file only: plaintext metadata (users, invites'
hashes, instance ids/owners/status/expiry/naming, audit) and SEALED blobs (configs,
specs, instance secrets under each user's passkey-derived key; see
sirosid_service/db.py). Keep it that way: never add a plaintext secret column.
"""
import os
import sys

NOT_CONFIGURED = 10
INCOMPLETE = 2


def _first(env, *names):
    for n in names:
        v = (env.get(n) or "").strip()
        if v:
            return v
    return ""


def _q(v: str) -> str:
    """A YAML double-quoted scalar. ${...} is left for Litestream to expand."""
    return '"' + v.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render(env) -> tuple:
    """(exit_code, text_or_message)."""
    db = _first(env, "SIROSID_DB") or "/data/sirosid.db"
    url = _first(env, "LITESTREAM_REPLICA_URL")
    bucket = _first(env, "LITESTREAM_BUCKET", "BUCKET_NAME")
    endpoint = _first(env, "LITESTREAM_ENDPOINT", "AWS_ENDPOINT_URL_S3")
    region = _first(env, "LITESTREAM_REGION", "AWS_REGION")
    path = _first(env, "LITESTREAM_PATH") or "sirosid.db"
    has_keys = bool(_first(env, "LITESTREAM_ACCESS_KEY_ID")) and bool(_first(env, "LITESTREAM_SECRET_ACCESS_KEY"))
    lines = ["# Generated by deploy/control-plane/litestream_config.py - no secrets in here.",
             "dbs:", f"  - path: {_q(db)}", "    replica:"]
    if url:
        lines.append(f"      url: {_q(url)}")
        if url.startswith("s3://"):
            if not has_keys:
                return INCOMPLETE, "LITESTREAM_REPLICA_URL is s3:// but LITESTREAM_ACCESS_KEY_ID/SECRET_ACCESS_KEY are not both set"
            lines += ["      access-key-id: ${LITESTREAM_ACCESS_KEY_ID}",
                      "      secret-access-key: ${LITESTREAM_SECRET_ACCESS_KEY}"]
        return 0, "\n".join(lines) + "\n"
    if not (bucket or endpoint):
        return NOT_CONFIGURED, "no replica configured (set BUCKET_NAME or LITESTREAM_BUCKET, or LITESTREAM_REPLICA_URL)"
    missing = [n for n, v in (("bucket (LITESTREAM_BUCKET/BUCKET_NAME)", bucket),
                              ("endpoint (LITESTREAM_ENDPOINT/AWS_ENDPOINT_URL_S3)", endpoint)) if not v]
    if not has_keys:
        missing.append("credentials (LITESTREAM_ACCESS_KEY_ID + LITESTREAM_SECRET_ACCESS_KEY, or AWS_*)")
    if missing:
        return INCOMPLETE, "replica half-configured, missing: " + "; ".join(missing)
    lines += ["      type: s3", f"      bucket: {_q(bucket)}", f"      path: {_q(path)}", f"      endpoint: {_q(endpoint)}",
              f"      region: {_q(region or 'auto')}",
              "      access-key-id: ${LITESTREAM_ACCESS_KEY_ID}",
              "      secret-access-key: ${LITESTREAM_SECRET_ACCESS_KEY}"]
    return 0, "\n".join(lines) + "\n"


def main(argv=None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    if len(argv) != 1:
        print(__doc__.split("\n\n")[0], file=sys.stderr)
        return 1
    env = dict(os.environ)
    # Tigris (fly storage create) names its keys AWS_*; Litestream's config names ours.
    for ours, theirs in (("LITESTREAM_ACCESS_KEY_ID", "AWS_ACCESS_KEY_ID"), ("LITESTREAM_SECRET_ACCESS_KEY", "AWS_SECRET_ACCESS_KEY")):
        env.setdefault(ours, env.get(theirs, ""))
    code, text = render(env)
    if code != 0:
        print(f"litestream: {text}", file=sys.stderr)
        return code
    fd = os.open(argv[0], os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o644)
    with os.fdopen(fd, "w") as f:
        f.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
