{{- /* ------------------------------------------------------------------------------------- */ -}}
{{- $ns := $.Release.Namespace -}}
{{- /* ------------------------------------------------------------------------------------- */ -}}
{{- define "getRandomKey" -}}
{{- randAlphaNum 32 -}}
{{- end -}}
{{- /* ------------------------------------------------------------------------------------- */ -}}
{{- define "getSecretProperty" -}}
{{- if or (not .secret) (not (hasKey .secret.data .property)) -}}
{{- include "getRandomKey" . -}}
{{- else -}}
{{- get .secret.data .property | b64dec -}}
{{- end -}}
{{- end -}}
{{- /* ------------------------------------------------------------------------------------- */ -}}
{{- define "getSecret" -}}
{{- $ns := index . 0 -}}
{{- $options := index . 1 -}}
{{- $outputProperties := dict -}}
{{- $secret := lookup "v1" "Secret" $ns $options.name -}}
{{- range $options.properties }}
{{-
  $_ := set $outputProperties . (
    include "getSecretProperty" (dict "secret" $secret "property" .)
  )
-}}
{{- end -}}
{{- $outputProperties | toYamlPretty -}}
{{- end -}}
{{- /* ------------------------------------------------------------------------------------- */ -}}
{{-
  $secretWalletBackendMain := (include "getSecret" (list $ns .Values.walletBackendMain) | fromYaml)
}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.walletBackendMain.name | quote }}
  namespace: {{ $ns | quote }}
data:
  jwtSecret: {{ $secretWalletBackendMain.jwtSecret | b64enc | quote }}
  adminToken: {{ $secretWalletBackendMain.adminToken | b64enc | quote }}
{{- /* ------------------------------------------------------------------------------------- */ -}}
{{-
  $secretIssuerRegistryMain := (
    include "getSecret" (list $ns .Values.issuerRegistryMain) | fromYaml
  )
}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.issuerRegistryMain.name | quote }}
  namespace: {{ $ns | quote }}
data:
  adminGuiPassword: {{ $secretIssuerRegistryMain.adminGuiPassword | b64enc | quote }}
{{- /* ------------------------------------------------------------------------------------- */ -}}
{{-
  $secretIssuerApigwMain := (include "getSecret" (list $ns .Values.issuerApigwMain) | fromYaml)
}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.issuerApigwMain.name | quote }}
  namespace: {{ $ns | quote }}
data:
  oidcProviderClientSecret: {{ $secretIssuerApigwMain.oidcProviderClientSecret | b64enc | quote }}
  apiAuthOidcClientSecret: {{ $secretIssuerApigwMain.apiAuthOidcClientSecret | b64enc | quote }}
{{- /* ------------------------------------------------------------------------------------- */ -}}
{{-
  $secretVerifierMain := (include "getSecret" (list $ns .Values.verifierMain) | fromYaml)
}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.verifierMain.name | quote }}
  namespace: {{ $ns | quote }}
data:
  oidcProviderSubjectSalt: {{ $secretVerifierMain.oidcProviderSubjectSalt | b64enc | quote }}
{{- /* ------------------------------------------------------------------------------------- */ -}}
{{- if .Values.r2psMain -}}
{{-
  $secretR2psMain := (include "getSecret" (list $ns .Values.r2psMain) | fromYaml)
}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.r2psMain.name | quote }}
  namespace: {{ $ns | quote }}
data:
  hsmPin: {{ $secretR2psMain.hsmPin | b64enc | quote }}
{{- end -}}
