#!/usr/bin/env python3
"""Render wallet-backend and go-trust (PDP) config from helm-charts/siros-id-stack.

sirosid-dev historically hand-maintained a parallel set of flat env vars
(docker-compose.test.yml's `wallet-backend` service, `--registry`/`--whitelist`
CLI flags for go-trust) that happen to drive the same underlying config schema
as the production Helm chart, but drift independently of it. Both
go-wallet-backend (pkg/config/config.go) and go-trust (pkg/config/config.go)
load one config struct via a YAML file (`--config`); Helm just renders that
YAML into a ConfigMap instead of a hand-written file.

This script renders the real chart with `helm template` (no cluster contact -
this only needs the chart on disk, see HELM_CHARTS_PATH) and extracts the
ConfigMap `data` blocks for wallet-backend and pdp verbatim, so any change to
the chart's templates/values flows into sirosid-dev automatically. The only
hand-written logic here is the small set of rewrites that are genuinely
environment-specific and have no values.yaml toggle to express them - see
patch_wallet_backend() per --target.

--target compose (default): sirosid-dev's local docker-compose stack.
  - wallet-backend's rp_origins/base_url/cors.allowed_origins/registry_url are
    built by helpers that hardcode an `https://` scheme (siros-id.origins.*,
    04-wallet-backend.yaml) - sirosid-dev serves everything over plain http.
  - wallet-backend's storage.mongodb is rendered for the MongoDB Community
    Operator (x509 mTLS SRV record) - sirosid-dev runs a single plain `mongo`
    container (docker-compose.vc-services.yml), so there's nothing to
    authenticate against and no cert volume to mount.
  PDP's whitelist is NOT patched here - see values-dev.yaml's `pdp:` block,
  which disables `default_whitelist` (hardcoded https placeholder hostnames)
  and supplies an equivalent whitelist of real compose-network URLs via
  `pdp.extraRegistries`, using the chart's own extension point instead of
  text surgery.

--target fly --env <name>: a named Fly.io environment (see scripts/fly-up.py).
  - Same https-scheme and mongodb-mTLS rewrites as compose, but pointed at
    Fly hostnames instead of localhost: `sirosid-<env>-<component>.fly.dev`
    (public, Fly automatic TLS) or `.internal` (Fly 6PN, private).
  - wallet-backend's public identity is `wallet-proxy`, not wallet-backend
    itself - wallet-backend has no Fly public service (see fly-up.py); a
    small nginx app (mirroring fixtures/wallet-proxy.conf) fronts it to also
    serve /.well-known/assetlinks.json for Android passkey verification,
    matching how local Android/tunnel testing already works (see
    docker-compose.test.yml's wallet-proxy service).
  - PDP's whitelist is likewise NOT patched here - the per-env values overlay
    generated by build_fly_values_overlay() supplies `pdp.extraRegistries`
    pointing at the env's own Fly-hosted vc-services, the same extension
    point values-dev.yaml uses for compose.

Output goes to fixtures/rendered/ (gitignored - regenerate with
`make render-helm-config` whenever helm-charts or values-dev.yaml change, or
via fly-up.py for a named environment). Secrets are generated once into
fixtures/rendered-secrets/ and reused on subsequent runs (idempotent, like
the chart's own `lookup`-based generator) - only used for --target compose;
--target fly's secrets live in Fly's own secret store (see fly_common.py).
"""
import argparse
import secrets
import string
from pathlib import Path

import yaml

from helm_render_lib import extract_configmap_data, helm_template, load_manifest_docs

SIROSID_DEV_ROOT = Path(__file__).resolve().parent.parent

# wallet-backend secret file names -> length. Mirrors
# helm-charts/siros-id-stack/config/secret_generator_template.yaml's use of
# `randAlphaNum 32` for these same keys.
WALLET_BACKEND_SECRETS = ["jwtSecret", "adminToken"]


def gen_secret(path: Path, length: int = 32) -> str:
    """Idempotent: an existing generated secret is reused, never rotated in place."""
    if path.exists():
        return path.read_text().strip()
    alphabet = string.ascii_letters + string.digits
    value = "".join(secrets.choice(alphabet) for _ in range(length))
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(value)
    return value


def patch_wallet_backend_compose(config: dict, extra_android_apk_key_hashes: list = None) -> dict:
    config["server"]["rp_id"] = "localhost"
    android_origins = [o for o in config["server"]["rp_origins"] if o.startswith("android:")]
    # Same reasoning as patch_wallet_backend_fly: debug builds / Play Store
    # signing keys (scripts/android_apps.py's .android-apps / --android-app)
    # are added on top of, not instead of, the production fingerprints
    # helm-charts' extraRpOrigins already carries.
    for apk_key_hash in extra_android_apk_key_hashes or []:
        origin = f"android:apk-key-hash:{apk_key_hash}"
        if origin not in android_origins:
            android_origins.append(origin)
    config["server"]["rp_origins"] = ["http://localhost:3000"] + android_origins
    config["server"]["base_url"] = "http://localhost:8080"
    config["server"]["cors"]["allowed_origins"] = ["http://localhost:3000"]
    config["trust"]["registry_url"] = "http://localhost:8080/registry"
    config["storage"]["mongodb"] = {
        "uri": "mongodb://mongodb:27017/wallet-backend",
        "tls_enabled": False,
        "database": "wallet-backend",
    }
    # The chart renders cert-manager Secret-volume paths (/wallet-provider-cert/*)
    # for a real Kubernetes deployment; docker-compose.helm-config.yml instead
    # bind-mounts the same fixtures/vc-pki files docker-compose.test.yml's
    # plain-env-var wallet-backend service uses, at these paths.
    config["wallet_provider"]["private_key_path"] = "/app/fixtures/wallet_provider_ec_private.pem"
    config["wallet_provider"]["certificate_path"] = "/app/fixtures/wallet_provider_ec.crt"
    config["wallet_provider"]["ca_cert_path"] = "/app/fixtures/rootCA.crt"
    # WIA-PoP aud claim validation (go-wallet-backend#221): must match
    # whatever URL the wallet SDK treats as "the backend", i.e. server.base_url
    # above - go-wallet-backend's config validation fails startup otherwise
    # once wia.enabled is true (hardcoded in the chart) with signing keys
    # configured (pkg/config/config.go).
    config["wallet_provider"]["wia"]["wallet_provider_uri"] = config["server"]["base_url"]
    return config


def patch_wallet_backend_fly(config: dict, env: str, extra_android_apk_key_hashes: list = None,
                              mongo_password: str = None, wallet_attestation: bool = False) -> dict:
    # wallet-proxy is wallet-backend's public identity on Fly for the ACTUAL
    # API (see module docstring) - but NOT for WebAuthn. The passkey ceremony
    # (navigator.credentials.create/get) executes in the browser at
    # wallet-frontend's own origin, and WebAuthn requires rp_id to equal (or
    # be a registrable-domain ancestor of) that calling origin - wallet-proxy
    # and wallet-frontend are unrelated sibling *.fly.dev subdomains sharing
    # no such ancestor, so an rp_id of wallet-proxy's domain can never work
    # from a page served at wallet-frontend's domain (confirmed: "passkey
    # creation failed" on every attempt). rp_id/rp_origins must reference
    # wallet-frontend's own domain instead - fly-up.py's WEBAUTHN_RPID env
    # var for the frontend must match this exactly.
    proxy_url = f"https://sirosid-{env}-wallet-proxy.fly.dev"
    frontend_url = f"https://sirosid-{env}-wallet-frontend.fly.dev"
    config["server"]["rp_id"] = f"sirosid-{env}-wallet-frontend.fly.dev"
    android_origins = [o for o in config["server"]["rp_origins"] if o.startswith("android:")]
    # Debug builds / Play Store signing keys the operator wants THIS
    # environment to also authenticate (fly-up.py's --android-app / auto-read
    # .env.android) - these are on top of, not instead of, the production
    # fingerprints helm-charts' extraRpOrigins already carries. Registering
    # only in assetlinks.json without also adding the origin here would pass
    # Android's OS-level Digital Asset Links check but still fail the actual
    # WebAuthn ceremony (wallet-backend never accepts the origin).
    for apk_key_hash in extra_android_apk_key_hashes or []:
        origin = f"android:apk-key-hash:{apk_key_hash}"
        if origin not in android_origins:
            android_origins.append(origin)
    config["server"]["rp_origins"] = [frontend_url] + android_origins
    config["server"]["base_url"] = proxy_url
    config["server"]["cors"]["allowed_origins"] = [frontend_url]
    # Unlike local dev (where frontend/backend share an origin via nginx path
    # routing, so the browser never sees a cross-origin request at all), Fly
    # puts wallet-frontend and wallet-backend on genuinely different
    # subdomains - every browser XHR from wallet-frontend is credentialed
    # (withCredentials: true) and cross-origin, so AllowCredentials must be
    # true or the browser rejects the CORS preflight outright (confirmed:
    # every passkey register/login request failed client-side with
    # "Access-Control-Allow-Credentials ... must be 'true'" before this was
    # set - this was never exercised by real-browser testing against a Fly
    # deployment before). Safe only because allowed_origins above is a
    # specific origin, never "*".
    config["server"]["cors"]["allow_credentials"] = True
    config["trust"]["pdp_url"] = f"http://sirosid-{env}-pdp.internal:8080"
    config["trust"]["registry_url"] = f"{proxy_url}/registry"
    # Authenticated - mongodb's own root user/password (fly-up.py generates
    # one per deploy and sets it via Fly secret + MONGO_INITDB_ROOT_* env
    # vars). Any app in the sirosfoundation org could otherwise reach this
    # database over Fly's shared 6PN network with zero credentials.
    mongo_auth = f"root:{mongo_password}@" if mongo_password else ""
    config["storage"]["mongodb"] = {
        "uri": f"mongodb://{mongo_auth}sirosid-{env}-mongodb.internal:27017/wallet-backend?authSource=admin",
        "tls_enabled": False,
        "database": "wallet-backend",
    }
    # The chart renders cert-manager Secret-volume paths (/wallet-provider-cert/*)
    # for a real Kubernetes deployment; fly-up.py's wallet-backend deploy_args
    # instead lands the private key as a Fly secret and the public cert/CA as
    # --file-local files at these paths (see the `name == "wallet-backend"`
    # branch in deploy_component()).
    config["wallet_provider"]["private_key_path"] = "/main-secrets/walletProviderKey"
    config["wallet_provider"]["certificate_path"] = "/main-config/walletProviderCert.pem"
    config["wallet_provider"]["ca_cert_path"] = "/main-config/walletProviderCA.pem"
    # WIA-PoP aud claim validation (go-wallet-backend#221): must match
    # whatever URL the wallet SDK treats as "the backend" - on Fly that's
    # proxy_url (server.base_url above), not wallet-backend's own
    # .internal-only hostname. Startup fails hard without this once
    # wia.enabled is true (hardcoded in the chart) with signing keys
    # configured (pkg/config/config.go's validation).
    config["wallet_provider"]["wia"]["wallet_provider_uri"] = config["server"]["base_url"]
    # Opt-in: authenticate to issuers via OAuth-Client-Attestation (the WIA
    # itself) instead of a pre-registered client_id - see
    # build_fly_values_overlay()'s wallet-providers whitelist entry, which
    # this pairs with. Requires an iss claim (below) rather than TS03's
    # x5c-derived identity: go-trust's whitelist registry only resolves
    # trust via JWKS-URL fetch (issuer/verifier/subject entries), it has no
    # custom-CA-pinning mechanism for a self-signed x5c chain, so x5c-based
    # identity can never actually resolve against this environment's PDP.
    if wallet_attestation:
        config["wallet_provider"]["wia"]["issuer"] = config["server"]["base_url"]
        config["wallet_provider"]["wia"]["omit_x5c"] = True
        # AS.ExternalURL builds the JWKS URL go-tokenauth fetches to verify
        # AS-issued access tokens (used by both HTTP resource endpoints and
        # the WebSocket engine's handshake auth) - left unset, it's "" and
        # the constructed URL is just the bare path "/auth/.well-known/jwks.json",
        # which can never resolve, so every AS-issued token (anonymous or
        # authenticated) fails signature verification with "Invalid or
        # expired token". Confirmed live: WS handshake rejected a token
        # /auth/token had just issued as 200 OK, for every retry.
        config.setdefault("as", {})["external_url"] = proxy_url
        # go-wallet-backend's own hardcoded fallback (ASConfig.SetDefaults,
        # used only when this is unset) is "rwl" - stale relative to what
        # wallet-frontend's real 'backend' token manifest requests
        # (AuthTokens.ts: tac "rwlid", i.e. read/write/list/insert/delete).
        # Every other real deployment already overrides this - both
        # docker-compose.test.yml and docker-compose.helm-config.yml set
        # WALLET_AS_DEFAULT_MAX_TAC=rwlidk (also including 'k'/delegate) -
        # this Fly path is the only one that never carried the same value
        # over, so passkey sessions here got MaxTAC=rwl and every real
        # token request 403ed with "requested permissions exceed session
        # maximum" the moment SPOCP/topology fixes let it get this far.
        config["as"]["default_max_tac"] = "rwlidk"
    return config


def build_fly_values_overlay(env: str, conformance: bool = False,
                              extra_trusted_issuers: list = None,
                              wallet_attestation: bool = False) -> dict:
    """Per-env values that can't live in the static values-fly.yaml because they
    embed the env name (hostnames, whitelist entries) - layered on top of it as
    an extra -f file. Mirrors values-dev.yaml's `pdp:` block, just parameterized.
    """
    # The whitelist must match whatever identity string actually appears as
    # the `iss` claim on issued credentials/tokens - that's vc-apigw's PUBLIC
    # url (patch-vc-config-fly.py sets both apigw.public_url and
    # issuer.issuer_url/jwt_attribute.issuer to it; vc-issuer's own hostname
    # is never presented as a credential issuer identity, wallets never reach
    # it directly - confirmed by go-trust logging a 404 fetching JWKS from
    # vc-issuer directly, since it isn't meant to be independently
    # discoverable). Real public https:// URLs, so unlike the docker-compose
    # target's local http-only whitelist, JWKS fetch works over real TLS here
    # without needing allow_http for these two entries.
    apigw_url = f"https://sirosid-{env}-vc-apigw.fly.dev"
    verifier_url = f"https://sirosid-{env}-vc-verifier.fly.dev"

    pid_issuers = [apigw_url]
    verifiers = [apigw_url, verifier_url]
    if conformance:
        # go-wallet-backend calls PDP for issuer trust at credential-offer
        # ACCEPTANCE time (internal/engine/oid4vci.go's evaluateTrust, keyed
        # on the offer's credential_issuer URL) - a separate, later check
        # from admin issuer registration, which grants no trust by itself.
        # Without this, every OID4VCI conformance module fails with
        # "untrusted issuer" the moment the wallet tries to accept the
        # suite's own offer, even though it was registered via
        # POST /admin/tenants/:id/issuers. The suite mints a fresh path per
        # test plan (https://.../test/a/<alias>/, alias varies), so a single
        # fixed URL can't cover it - go-trust's whitelist supports a
        # trailing-`*` prefix match (see pkg/registry/static/whitelist.go's
        # matchesList), which does. Added to both lists since the suite acts
        # as issuer (OID4VCI) and verifier (OID4VP) from the same domain,
        # and both spec suites already exist in sirosid-tests.
        conformance_prefix = f"https://sirosid-{env}-conformance.fly.dev/*"
        pid_issuers.append(conformance_prefix)
        verifiers.append(conformance_prefix)

    # Ad-hoc external issuers for interop testing (e.g. a third-party mdoc
    # issuer at a conference/plugfest) - trusted as issuers only, not
    # verifiers, since there's no equivalent need to accept presentation
    # requests from them.
    #
    # These MUST also land in pid_issuers (the whitelist registry), not only
    # mdociaca.issuer_allowlist: go-wallet-backend's offer-acceptance-time
    # issuer check (evaluateTrust -> AuthZEN "credential-issuer" action) is a
    # *resolution-only* request (no key material yet), and go-trust's
    # RegistryManager.getApplicableRegistriesWithPolicy() only queries
    # registries where SupportsResolutionOnly() is true - mdociaca.Registry
    # explicitly returns false there ("requires X5C chains"), so mdociaca is
    # never even consulted for this check, whitelist-membership or not.
    # Confirmed by a live PDP log: "Strategy[FirstMatch]: evaluating
    # registry" only ever listed "... Fly whitelist", never mdociaca, for
    # this action - mdociaca only matters for the LATER, key-bearing check at
    # actual credential-response signature/cert-chain verification time.
    #
    # The whitelist registry's own Evaluate() only needs `r.resolvedLists`
    # (a plain config string/pattern match) for a resolution-only request -
    # it never touches `r.keyHashes` (the fetched-JWKS map) at all in that
    # path - so membership alone is enough; a working JWKS endpoint for the
    # entity is NOT required for this to pass. The cost of pid_issuers
    # membership is purely go-trust's own missing-timeout bug: its initial,
    # synchronous Refresh(context.Background()) at boot (StartRefreshLoop,
    # called before cmd/gt's r.Run() starts the HTTP listener) will spend
    # several minutes failing to fetch JWKS for an issuer with no such
    # endpoint before giving up and continuing - slow (and compounding with
    # vc-apigw/vc-verifier's own pre-existing slow-JWKS-timeout issue, see
    # project_pdp_mdoc_issuer_whitelist_hang memory) but not fatal: the
    # registry keeps working via resolution-only checks regardless of
    # whether the fetch ever succeeds.
    if extra_trusted_issuers:
        pid_issuers.extend(extra_trusted_issuers)

    # This environment's own wallet-backend, trusted as a wallet_provider
    # (go-trust's RoleWalletProvider) so SUNET/vc's WalletAttestationEvaluator
    # can authenticate wallets via their WIA alone - no pre-registered
    # client_id (see patch_wallet_backend_fly's wia.issuer/omit_x5c and
    # patch-vc-config-fly.py's apigw.trust.wallet_attestation). Only added
    # when wallet_attestation is requested, since it's new/unvalidated and
    # every other environment should keep today's behavior unchanged.
    wallet_providers = []
    if wallet_attestation:
        wallet_providers.append(f"https://sirosid-{env}-wallet-proxy.fly.dev")

    lists = {
        "pid-issuers": pid_issuers,
        "verifiers": verifiers,
    }
    actions = {
        "pid-provider": "pid-issuers",
        "credential-issuer": "pid-issuers",
        "verifier": "verifiers",
        "credential-verifier": "verifiers",
    }
    if wallet_providers:
        lists["wallet-providers"] = wallet_providers
        actions["wallet_provider"] = "wallet-providers"

    return {
        "tenant": {"id": env},
        "pdp": {
            "default_whitelist": False,
            "externalUrl": f"http://sirosid-{env}-pdp.internal:8080",
            "extraRegistries": {
                "whitelist": {
                    "enabled": True,
                    "name": f"sirosid-{env} Fly whitelist",
                    "description": "Fly-hosted vc-services URLs (rendered from helm-charts schema)",
                    "lists": lists,
                    "actions": actions,
                },
                # The whitelist registry above only ever caches JWT-signing
                # keys (via jwt-vc-issuer/jwks_uri discovery) - it has no
                # notion of an issuer's mdoc_iacas_uri. An mdoc issuer's
                # extractIssuerKeyMaterial (go-wallet-backend) prioritizes
                # mdoc_iacas_uri over JWKS, so any issuer offering mso_mdoc
                # credentials needs this separate registry too, or trust
                # evaluation permanently denies with "no keys cached for
                # entity" regardless of whitelist membership. Reuses the same
                # pid_issuers list as the trust boundary (not "trust any
                # issuer that publishes a valid IACA").
                "mdociaca": {
                    "enabled": True,
                    "name": f"sirosid-{env} mDOC IACA registry",
                    "description": "IACA cert validation for mso_mdoc issuers (rendered from helm-charts schema)",
                    "issuer_allowlist": pid_issuers,
                },
            },
        },
    }


def render(target: str, chart_dir: Path, env: str = None, android_apk_key_hashes: list = None,
           namespace: str = "sirosid-dev", out_dir: Path = None, secrets_dir: Path = None,
           mongo_password: str = None, conformance: bool = False,
           extra_trusted_issuers: list = None, wallet_attestation: bool = False) -> list:
    """Does the actual `helm template` + extract + patch + write-files work for
    one target; returns the rendered manifest's docs so a caller that also
    needs OTHER parts of the same manifest (fly-up.py: image refs, mongo
    version, wallet-frontend's Android/iOS wellknown values) can reuse this
    one render instead of invoking `helm template` a second time.
    """
    if target == "fly" and not env:
        raise ValueError("target 'fly' requires env")

    out_dir = Path(out_dir) if out_dir else SIROSID_DEV_ROOT / "fixtures" / "rendered"

    # helm template applies the chart's own values.yaml automatically; only
    # overrides need to be passed explicitly.
    if target == "compose":
        values_files = [SIROSID_DEV_ROOT / "values-dev.yaml"]
    else:
        values_files = [SIROSID_DEV_ROOT / "values-fly.yaml"]
        out_dir = out_dir / f"fly-{env}"
        out_dir.mkdir(parents=True, exist_ok=True)
        overlay_path = out_dir / "values.generated.yaml"
        overlay_path.write_text(yaml.dump(
            build_fly_values_overlay(env, conformance, extra_trusted_issuers, wallet_attestation), sort_keys=False))
        values_files.append(overlay_path)

    manifest = helm_template(chart_dir, values_files, namespace if target == "compose" else f"sirosid-{env}")
    docs = load_manifest_docs(manifest)

    out_dir.mkdir(parents=True, exist_ok=True)

    # --- wallet-backend ---
    wb_data = extract_configmap_data(docs, "wallet-backend-main")
    backend_cfg = yaml.safe_load(wb_data["backend.yaml"])
    if target == "compose":
        backend_cfg = patch_wallet_backend_compose(backend_cfg, android_apk_key_hashes)
    else:
        backend_cfg = patch_wallet_backend_fly(backend_cfg, env, android_apk_key_hashes, mongo_password,
                                                wallet_attestation)
    (out_dir / "wallet-backend.yaml").write_text(yaml.dump(backend_cfg, sort_keys=False))
    (out_dir / "wallet-backend-registry.yaml").write_text(wb_data["registry.yaml"])
    print(f"wrote {out_dir / 'wallet-backend.yaml'}")
    print(f"wrote {out_dir / 'wallet-backend-registry.yaml'}")

    # registry.yaml's local_overrides always points at /vctms - Helm mounts this
    # from a `vctms` ConfigMap (created even when empty), so the directory must
    # exist here too or the registry provider fails to start (`stat /vctms: no
    # such file or directory`), even with features.credentialTypes: {}.
    (out_dir / "vctms").mkdir(exist_ok=True)

    # registry.yaml's cache.path lives under /cache, which Helm mounts as an
    # emptyDir (writable by the pod's fsGroup). go-wallet-backend runs as
    # uid 65532 (Dockerfile:45), and a bind-mounted dir defaults to the host
    # user's ownership, so it must be made world-writable here explicitly.
    cache_dir = out_dir / "cache"
    cache_dir.mkdir(exist_ok=True)
    cache_dir.chmod(0o777)

    # --- pdp ---
    pdp_data = extract_configmap_data(docs, "pdp-main")
    (out_dir / "pdp.yaml").write_text(pdp_data["config.yaml"])
    print(f"wrote {out_dir / 'pdp.yaml'}")

    if target == "compose":
        # --- secrets (mirrors config/secret_generator_template.yaml's randAlphaNum 32) ---
        secrets_dir = Path(secrets_dir) if secrets_dir else SIROSID_DEV_ROOT / "fixtures" / "rendered-secrets"
        for name in WALLET_BACKEND_SECRETS:
            gen_secret(secrets_dir / name)
        print(f"secrets ready in {secrets_dir} ({', '.join(WALLET_BACKEND_SECRETS)})")
    else:
        print("--target fly: secrets are handled by fly-up.py (fly secrets set), not here")

    return docs


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--chart-dir", default=str(SIROSID_DEV_ROOT.parent / "helm-charts" / "siros-id-stack"),
                         help="Path to the siros-id-stack chart (default: ../helm-charts/siros-id-stack)")
    parser.add_argument("--target", choices=["compose", "fly"], default="compose")
    parser.add_argument("--env", help="Environment name, required for --target fly (e.g. test1)")
    parser.add_argument("--android-apk-key-hash", action="append", default=[],
                         help="base64url apk-key-hash (no padding) to add to wallet-backend's "
                              "rp_origins, on top of the production ones helm-charts already "
                              "carries - repeatable, applies to both --target compose and "
                              "--target fly. See scripts/android_apps.py (.android-apps / "
                              "--android-app) for the developer-facing (colon-hex) form of this "
                              "- the Makefile passes its output through here for both targets.")
    parser.add_argument("--mongo-password", default=None,
                         help="--target fly only: mongodb root password (fly-up.py generates and sets "
                              "this as a Fly secret on the mongodb app itself; passed here so "
                              "wallet-backend's config embeds a matching authenticated connection URI).")
    parser.add_argument("--conformance", action="store_true",
                         help="--target fly only: also whitelist the conformance suite's issuer/verifier "
                              "identity (https://sirosid-<env>-conformance.fly.dev/*) with PDP, so the "
                              "wallet accepts credential offers/presentation requests from it during "
                              "OID4VCI/OID4VP conformance testing - see build_fly_values_overlay().")
    parser.add_argument("--namespace", default="sirosid-dev")
    parser.add_argument("--out-dir", default=str(SIROSID_DEV_ROOT / "fixtures" / "rendered"))
    parser.add_argument("--secrets-dir", default=str(SIROSID_DEV_ROOT / "fixtures" / "rendered-secrets"))
    args = parser.parse_args()

    if args.target == "fly" and not args.env:
        parser.error("--target fly requires --env <name>")

    chart_dir = Path(args.chart_dir)
    if not chart_dir.is_dir():
        raise SystemExit(
            f"Chart not found at {chart_dir} - clone sibling repo "
            f"'helm-charts' next to sirosid-dev, or pass --chart-dir "
            f"(see HELM_CHARTS_PATH in the Makefile)"
        )

    render(args.target, chart_dir, env=args.env, android_apk_key_hashes=args.android_apk_key_hash,
           namespace=args.namespace, out_dir=Path(args.out_dir), secrets_dir=Path(args.secrets_dir),
           mongo_password=args.mongo_password, conformance=args.conformance)


if __name__ == "__main__":
    main()
