#!/usr/bin/env python3
"""Render wallet-backend and go-trust (PDP) config from helm-charts/siros-id-stack.

sirosid-dev historically hand-maintained a parallel set of flat env vars
(docker-compose.test.yml's `wallet-backend` service, `--registry`/`--whitelist`
CLI flags for go-trust) that happen to drive the same underlying config schema
as the production Helm chart, but drift independently of it. Both
go-wallet-backend (pkg/config/config.go) and go-trust (pkg/config/config.go)
load one config struct via a YAML file (`--config`); Helm just renders that
YAML into a ConfigMap instead of a hand-written file.

This script renders the real chart with `helm template` (no cluster contact -
this only needs the chart on disk, see HELM_CHARTS_PATH) and extracts the
ConfigMap `data` blocks for wallet-backend and pdp verbatim, so any change to
the chart's templates/values flows into sirosid-dev automatically. The only
hand-written logic here is the small set of rewrites that are genuinely
environment-specific and have no values.yaml toggle to express them - see
patch_wallet_backend() per --target.

--target compose (default): sirosid-dev's local docker-compose stack.
  - wallet-backend's rp_origins/base_url/cors.allowed_origins/registry_url are
    built by helpers that hardcode an `https://` scheme (siros-id.origins.*,
    04-wallet-backend.yaml) - sirosid-dev serves everything over plain http.
  - wallet-backend's storage.mongodb is rendered for the MongoDB Community
    Operator (x509 mTLS SRV record) - sirosid-dev runs a single plain `mongo`
    container (docker-compose.vc-services.yml), so there's nothing to
    authenticate against and no cert volume to mount.
  PDP's whitelist is NOT patched here - see values-dev.yaml's `pdp:` block,
  which disables `default_whitelist` (hardcoded https placeholder hostnames)
  and supplies an equivalent whitelist of real compose-network URLs via
  `pdp.extraRegistries`, using the chart's own extension point instead of
  text surgery.

--target fly --env <name>: a named Fly.io environment (see scripts/fly-up.py).
  - Same https-scheme and mongodb-mTLS rewrites as compose, but pointed at
    Fly hostnames instead of localhost: `sirosid-<env>-<component>.fly.dev`
    (public, Fly automatic TLS) or `.internal` (Fly 6PN, private).
  - wallet-backend's public identity is `wallet-proxy`, not wallet-backend
    itself - wallet-backend has no Fly public service (see fly-up.py); a
    small nginx app (mirroring fixtures/wallet-proxy.conf) fronts it to also
    serve /.well-known/assetlinks.json for Android passkey verification,
    matching how local Android/tunnel testing already works (see
    docker-compose.test.yml's wallet-proxy service).
  - PDP's whitelist is likewise NOT patched here - the per-env values overlay
    generated by build_fly_values_overlay() supplies `pdp.extraRegistries`
    pointing at the env's own Fly-hosted vc-services, the same extension
    point values-dev.yaml uses for compose.

Output goes to fixtures/rendered/ (gitignored - regenerate with
`make render-helm-config` whenever helm-charts or values-dev.yaml change, or
via fly-up.py for a named environment). Secrets are generated once into
fixtures/rendered-secrets/ and reused on subsequent runs (idempotent, like
the chart's own `lookup`-based generator) - only used for --target compose;
--target fly's secrets live in Fly's own secret store (see fly_common.py).
"""
import argparse
import secrets
import string
import sys
import tempfile
from pathlib import Path

import yaml

from helm_render_lib import extract_configmap_data, helm_template, load_manifest_docs

SIROSID_DEV_ROOT = Path(__file__).resolve().parent.parent

# wallet-backend secret file names -> length. Mirrors
# helm-charts/siros-id-stack/config/secret_generator_template.yaml's use of
# `randAlphaNum 32` for these same keys.
WALLET_BACKEND_SECRETS = ["jwtSecret", "adminToken"]


def gen_secret(path: Path, length: int = 32) -> str:
    """Idempotent: an existing generated secret is reused, never rotated in place."""
    if path.exists():
        return path.read_text().strip()
    alphabet = string.ascii_letters + string.digits
    value = "".join(secrets.choice(alphabet) for _ in range(length))
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(value)
    return value


def patch_wallet_backend_compose(config: dict) -> dict:
    config["server"]["rp_id"] = "localhost"
    android_origins = [o for o in config["server"]["rp_origins"] if o.startswith("android:")]
    config["server"]["rp_origins"] = ["http://localhost:3000"] + android_origins
    config["server"]["base_url"] = "http://localhost:8080"
    config["server"]["cors"]["allowed_origins"] = ["http://localhost:3000"]
    config["trust"]["registry_url"] = "http://localhost:8080/registry"
    config["storage"]["mongodb"] = {
        "uri": "mongodb://mongodb:27017/wallet-backend",
        "tls_enabled": False,
        "database": "wallet-backend",
    }
    return config


def patch_wallet_backend_fly(config: dict, env: str) -> dict:
    # wallet-proxy is wallet-backend's public identity on Fly (see module docstring).
    proxy_url = f"https://sirosid-{env}-wallet-proxy.fly.dev"
    frontend_url = f"https://sirosid-{env}-wallet-frontend.fly.dev"
    config["server"]["rp_id"] = f"sirosid-{env}-wallet-proxy.fly.dev"
    android_origins = [o for o in config["server"]["rp_origins"] if o.startswith("android:")]
    config["server"]["rp_origins"] = [proxy_url] + android_origins
    config["server"]["base_url"] = proxy_url
    config["server"]["cors"]["allowed_origins"] = [frontend_url]
    config["trust"]["pdp_url"] = f"http://sirosid-{env}-pdp.internal:8080"
    config["trust"]["registry_url"] = f"{proxy_url}/registry"
    config["storage"]["mongodb"] = {
        "uri": f"mongodb://sirosid-{env}-mongodb.internal:27017/wallet-backend",
        "tls_enabled": False,
        "database": "wallet-backend",
    }
    return config


def build_fly_values_overlay(env: str) -> dict:
    """Per-env values that can't live in the static values-fly.yaml because they
    embed the env name (hostnames, whitelist entries) - layered on top of it as
    an extra -f file. Mirrors values-dev.yaml's `pdp:` block, just parameterized.
    """
    # The whitelist must match whatever identity string actually appears as
    # the `iss` claim on issued credentials/tokens - that's vc-apigw's PUBLIC
    # url (patch-vc-config-fly.py sets both apigw.public_url and
    # issuer.issuer_url/jwt_attribute.issuer to it; vc-issuer's own hostname
    # is never presented as a credential issuer identity, wallets never reach
    # it directly - confirmed by go-trust logging a 404 fetching JWKS from
    # vc-issuer directly, since it isn't meant to be independently
    # discoverable). Real public https:// URLs, so unlike the docker-compose
    # target's local http-only whitelist, JWKS fetch works over real TLS here
    # without needing allow_http for these two entries.
    apigw_url = f"https://sirosid-{env}-vc-apigw.fly.dev"
    verifier_url = f"https://sirosid-{env}-vc-verifier.fly.dev"

    return {
        "tenant": {"id": env},
        "pdp": {
            "default_whitelist": False,
            "externalUrl": f"http://sirosid-{env}-pdp.internal:8080",
            "extraRegistries": {
                "whitelist": {
                    "enabled": True,
                    "name": f"sirosid-{env} Fly whitelist",
                    "description": "Fly-hosted vc-services URLs (rendered from helm-charts schema)",
                    "lists": {
                        "pid-issuers": [apigw_url],
                        "verifiers": [apigw_url, verifier_url],
                    },
                    "actions": {
                        "pid-provider": "pid-issuers",
                        "credential-issuer": "pid-issuers",
                        "verifier": "verifiers",
                        "credential-verifier": "verifiers",
                    },
                },
            },
        },
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--chart-dir", default=str(SIROSID_DEV_ROOT.parent / "helm-charts" / "siros-id-stack"),
                         help="Path to the siros-id-stack chart (default: ../helm-charts/siros-id-stack)")
    parser.add_argument("--target", choices=["compose", "fly"], default="compose")
    parser.add_argument("--env", help="Environment name, required for --target fly (e.g. test1)")
    parser.add_argument("--namespace", default="sirosid-dev")
    parser.add_argument("--out-dir", default=str(SIROSID_DEV_ROOT / "fixtures" / "rendered"))
    parser.add_argument("--secrets-dir", default=str(SIROSID_DEV_ROOT / "fixtures" / "rendered-secrets"))
    args = parser.parse_args()

    if args.target == "fly" and not args.env:
        parser.error("--target fly requires --env <name>")

    chart_dir = Path(args.chart_dir)
    if not chart_dir.is_dir():
        raise SystemExit(
            f"Chart not found at {chart_dir} - clone sibling repo "
            f"'helm-charts' next to sirosid-dev, or pass --chart-dir "
            f"(see HELM_CHARTS_PATH in the Makefile)"
        )

    # helm template applies the chart's own values.yaml automatically; only
    # overrides need to be passed explicitly.
    if args.target == "compose":
        values_files = [SIROSID_DEV_ROOT / "values-dev.yaml"]
        out_dir = Path(args.out_dir)
    else:
        values_files = [SIROSID_DEV_ROOT / "values-fly.yaml"]
        out_dir = Path(args.out_dir) / f"fly-{args.env}"
        out_dir.mkdir(parents=True, exist_ok=True)
        overlay_path = out_dir / "values.generated.yaml"
        overlay_path.write_text(yaml.dump(build_fly_values_overlay(args.env), sort_keys=False))
        values_files.append(overlay_path)

    manifest = helm_template(chart_dir, values_files, args.namespace if args.target == "compose" else f"sirosid-{args.env}")
    docs = load_manifest_docs(manifest)

    out_dir.mkdir(parents=True, exist_ok=True)

    # --- wallet-backend ---
    wb_data = extract_configmap_data(docs, "wallet-backend-main")
    backend_cfg = yaml.safe_load(wb_data["backend.yaml"])
    if args.target == "compose":
        backend_cfg = patch_wallet_backend_compose(backend_cfg)
    else:
        backend_cfg = patch_wallet_backend_fly(backend_cfg, args.env)
    (out_dir / "wallet-backend.yaml").write_text(yaml.dump(backend_cfg, sort_keys=False))
    (out_dir / "wallet-backend-registry.yaml").write_text(wb_data["registry.yaml"])
    print(f"wrote {out_dir / 'wallet-backend.yaml'}")
    print(f"wrote {out_dir / 'wallet-backend-registry.yaml'}")

    # registry.yaml's local_overrides always points at /vctms - Helm mounts this
    # from a `vctms` ConfigMap (created even when empty), so the directory must
    # exist here too or the registry provider fails to start (`stat /vctms: no
    # such file or directory`), even with features.credentialTypes: {}.
    (out_dir / "vctms").mkdir(exist_ok=True)

    # registry.yaml's cache.path lives under /cache, which Helm mounts as an
    # emptyDir (writable by the pod's fsGroup). go-wallet-backend runs as
    # uid 65532 (Dockerfile:45), and a bind-mounted dir defaults to the host
    # user's ownership, so it must be made world-writable here explicitly.
    cache_dir = out_dir / "cache"
    cache_dir.mkdir(exist_ok=True)
    cache_dir.chmod(0o777)

    # --- pdp ---
    pdp_data = extract_configmap_data(docs, "pdp-main")
    (out_dir / "pdp.yaml").write_text(pdp_data["config.yaml"])
    print(f"wrote {out_dir / 'pdp.yaml'}")

    if args.target == "compose":
        # --- secrets (mirrors config/secret_generator_template.yaml's randAlphaNum 32) ---
        secrets_dir = Path(args.secrets_dir)
        for name in WALLET_BACKEND_SECRETS:
            gen_secret(secrets_dir / name)
        print(f"secrets ready in {secrets_dir} ({', '.join(WALLET_BACKEND_SECRETS)})")
    else:
        print("--target fly: secrets are handled by fly-up.py (fly secrets set), not here")


if __name__ == "__main__":
    main()
