#!/usr/bin/env python3
"""Render wallet-backend and go-trust (PDP) config from the siros-id-stack chart.

sirosid-dev historically hand-maintained a parallel set of flat env vars
(docker-compose.test.yml's `wallet-backend` service, `--registry`/`--whitelist`
CLI flags for go-trust) that happen to drive the same underlying config schema
as the production Helm chart, but drift independently of it. Both
go-wallet-backend (pkg/config/config.go) and go-trust (pkg/config/config.go)
load one config struct via a YAML file (`--config`); Helm just renders that
YAML into a ConfigMap instead of a hand-written file.

This script renders the real chart with `helm template` (no cluster contact -
this only needs the chart on disk, see SIROS_ID_STACK_PATH) and extracts the
ConfigMap `data` blocks for wallet-backend and pdp verbatim, so any change to
the chart's templates/values flows into sirosid-dev automatically. The only
hand-written logic here is the small set of rewrites that are genuinely
environment-specific and have no values.yaml toggle to express them - see
patch_wallet_backend() per --target.

--target compose (default): sirosid-dev's local docker-compose stack.
  - wallet-backend's rp_origins/base_url/cors.allowed_origins/registry_url are
    built by helpers that hardcode an `https://` scheme (siros-id.origins.*,
    04-wallet-backend.yaml) - sirosid-dev serves everything over plain http.
  - wallet-backend's storage.mongodb is rendered for the MongoDB Community
    Operator (x509 mTLS SRV record) - sirosid-dev runs a single plain `mongo`
    container (docker-compose.vc-services.yml), so there's nothing to
    authenticate against and no cert volume to mount.
  PDP's whitelist is NOT patched here - see values-dev.yaml's `pdp:` block,
  which disables `default_whitelist` (hardcoded https placeholder hostnames)
  and supplies an equivalent whitelist of real compose-network URLs via
  `pdp.extraRegistries`, using the chart's own extension point instead of
  text surgery.

--target fly --env <name>: a named Fly.io environment (see scripts/fly-up.py).
  - Same https-scheme and mongodb-mTLS rewrites as compose, but pointed at
    Fly hostnames instead of localhost: `sirosid-<env>-<component>.fly.dev`
    (public, Fly automatic TLS) or `.internal` (Fly 6PN, private).
  - wallet-backend's public identity is `wallet-proxy`, not wallet-backend
    itself - wallet-backend has no Fly public service (see fly-up.py); a
    small nginx app (mirroring fixtures/wallet-proxy.conf) fronts it to also
    serve /.well-known/assetlinks.json for Android passkey verification,
    matching how local Android/tunnel testing already works (see
    docker-compose.test.yml's wallet-proxy service).
  - PDP's whitelist is likewise NOT patched here - the per-env values overlay
    generated by build_fly_values_overlay() supplies `pdp.extraRegistries`
    pointing at the env's own Fly-hosted vc-services, the same extension
    point values-dev.yaml uses for compose.

Output goes to fixtures/rendered/ (gitignored - regenerate with
`make render-helm-config` whenever siros-id-stack or values-dev.yaml change, or
via fly-up.py for a named environment). Secrets are generated once into
fixtures/rendered-secrets/ and reused on subsequent runs (idempotent, like
the chart's own `lookup`-based generator) - only used for --target compose;
--target fly's secrets live in Fly's own secret store (see fly_common.py).
"""
import argparse
import secrets
import string
import subprocess
import sys
from pathlib import Path

import yaml

import fly_common
import vc_render
from helm_render_lib import extract_configmap_data, helm_template, load_manifest_docs

SIROSID_DEV_ROOT = Path(__file__).resolve().parent.parent

# wallet-backend secret file names -> length. Mirrors
# siros-id-stack/config/secret_generator_template.yaml's use of
# `randAlphaNum 32` for these same keys.
WALLET_BACKEND_SECRETS = ["jwtSecret", "adminToken"]


# Markers that must be present in ../siros-id-stack for values-base.yaml to
# render at all. A chart older than these fails deep inside `helm template`
# with an error naming one of the chart's own template lines and no hint that
# the reader's checkout is simply out of date - which is exactly what happened
# the first time someone pulled this repo without pulling the chart:
#
#   execution error at (siros-id-stack/templates/03-cred-common.yaml:12:24):
#   Object must contain non-empty .data or .file property
#
# (An mdoc credential type declares `mdocSchema` and no `vctm`, so the old
# template's unconditional dataOrFile on `.vctm` got nil.)
REQUIRED_CHART_MARKERS = [
    ("templates/_helpers.tpl", "siros-id.vc.renderConfig",
     "per-service config rendering with an extraConfig escape hatch"),
    ("templates/_helpers.tpl", "mdocSchema",
     "ISO 18013-5 mdoc credential types (features.credentialTypes[].mdocSchema)"),
]


def check_chart_supported(chart_dir: Path):
    """Fail early and legibly when ../siros-id-stack predates what this repo needs."""
    missing = [
        (marker, why) for rel, marker, why in REQUIRED_CHART_MARKERS
        if marker not in (chart_dir / rel).read_text(errors="ignore")
    ] if (chart_dir / "templates" / "_helpers.tpl").is_file() else []
    if not missing:
        return
    raise SystemExit(
        f"\nERROR: the chart at {chart_dir} is too old for this repo's values-base.yaml.\n"
        + "".join(f"  missing: {m}  ({why})\n" for m, why in missing)
        + "\n" + _chart_update_hint(chart_dir)
        + "\n  Without this, `helm template` fails inside the chart's own templates with\n"
          "  no indication that the checkout is the problem.\n")


def _git(chart_dir: Path, *args) -> str:
    try:
        r = subprocess.run(["git", "-C", str(chart_dir), *args], capture_output=True, text=True)
        return r.stdout.strip() if r.returncode == 0 else ""
    except FileNotFoundError:
        return ""


def _chart_update_hint(chart_dir: Path) -> str:
    """Say which of `make setup`'s three outcomes applies here.

    `make setup` fast-forwards the chart, but only when it is on main and the
    pull succeeds; the other two cases print a coloured note and setup carries
    on, which is easy to miss in its output. Naming the actual case turns
    "run make setup" into something the reader can act on.
    """
    if not (chart_dir / ".git").exists():
        return (f"  {chart_dir} is not a git checkout, so `make setup` cannot update it.\n"
                "  Replace it with a clone of sirosfoundation/siros-id-stack, or point\n"
                "  SIROS_ID_STACK_PATH=<dir> at one.\n")
    branch = _git(chart_dir, "branch", "--show-current")
    dirty = bool(_git(chart_dir, "status", "--porcelain"))
    if branch != "main":
        return (f"  It is on branch '{branch or 'a detached HEAD'}', not main - `make setup`\n"
                "  deliberately leaves it alone in that case (so a PR branch someone is\n"
                "  testing is not yanked out from under them) and only prints a note.\n"
                "  Either switch it back:\n"
                f"    git -C {chart_dir} checkout main && git -C {chart_dir} pull\n"
                "  or point at another checkout with SIROS_ID_STACK_PATH=<dir>.\n")
    if dirty:
        return ("  It is on main but has local changes, so `make setup`'s\n"
                "  `git pull --ff-only` cannot fast-forward it (setup reports this as\n"
                "  'update failed' and continues). Stash or commit them, then:\n"
                f"    git -C {chart_dir} pull\n")
    return ("  It is on main and clean, so it just needs pulling:\n"
            "    make setup\n"
            f"  or: git -C {chart_dir} pull\n")


def gen_secret(path: Path, length: int = 32) -> str:
    """Idempotent: an existing generated secret is reused, never rotated in place."""
    if path.exists():
        return path.read_text().strip()
    alphabet = string.ascii_letters + string.digits
    value = "".join(secrets.choice(alphabet) for _ in range(length))
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(value)
    return value


def patch_wallet_backend_compose(config: dict, extra_android_apk_key_hashes: list = None) -> dict:
    config["server"]["rp_id"] = "localhost"
    android_origins = [o for o in config["server"]["rp_origins"] if o.startswith("android:")]
    # Same reasoning as patch_wallet_backend_fly: debug builds / Play Store
    # signing keys (scripts/android_apps.py's .android-apps / --android-app)
    # are added on top of, not instead of, the production fingerprints
    # siros-id-stack's extraRpOrigins already carries.
    for apk_key_hash in extra_android_apk_key_hashes or []:
        origin = f"android:apk-key-hash:{apk_key_hash}"
        if origin not in android_origins:
            android_origins.append(origin)
    config["server"]["rp_origins"] = ["http://localhost:3000"] + android_origins
    config["server"]["base_url"] = "http://localhost:8080"
    # The chart's `as:` block derives its external_url/issuer from the
    # walletBackend hostname with a hardcoded https:// scheme, same as
    # server.base_url above - and the AS issuer ends up in every access token
    # it mints, so it has to be the URL clients actually reach.
    if config.get("as"):
        config["as"]["external_url"] = config["server"]["base_url"]
        config["as"]["issuer"] = config["server"]["base_url"]
    config["server"]["cors"]["allowed_origins"] = ["http://localhost:3000"]
    config["trust"]["registry_url"] = "http://localhost:8080/registry"
    config["storage"]["mongodb"] = {
        "uri": "mongodb://mongodb:27017/wallet-backend",
        "tls_enabled": False,
        "database": "wallet-backend",
    }
    # The chart renders cert-manager Secret-volume paths (/wallet-provider-cert/*)
    # for a real Kubernetes deployment; docker-compose.helm-config.yml instead
    # bind-mounts the same fixtures/vc-pki files docker-compose.test.yml's
    # plain-env-var wallet-backend service uses, at these paths.
    # siros-id-stack's wallet-backend template doesn't render a
    # `wallet_provider` block at all today (see CLAUDE.md's wallet_provider.wia
    # gotcha) - setdefault() so this still patches cleanly once it does,
    # without requiring a chart change first.
    wallet_provider = config.setdefault("wallet_provider", {})
    wallet_provider["private_key_path"] = "/app/fixtures/wallet_provider_ec_private.pem"
    wallet_provider["certificate_path"] = "/app/fixtures/wallet_provider_ec.crt"
    wallet_provider["ca_cert_path"] = "/app/fixtures/rootCA.crt"
    # go-wallet-backend's own defaultConfig() (pkg/config/config.go) - not the
    # chart, not this script - defaults wia.enabled to true and wia.mode to
    # "etsi" with no wallet_version default, so an absent/empty `wia` block
    # still fails Validate()'s "wallet_version is required" check at startup.
    # docker-compose.test.yml's hand-maintained wallet-backend service already
    # disables WIA the same way (WALLET_WALLET_PROVIDER_WIA_ENABLED=false) -
    # Key Attestation doesn't require it (wallet_instance_id is optional) -
    # mirrored here for the helm-rendered config path.
    wia = wallet_provider.setdefault("wia", {})
    wia["enabled"] = False
    # WIA-PoP aud claim validation (go-wallet-backend#221): must match
    # whatever URL the wallet SDK treats as "the backend", i.e. server.base_url
    # above - only matters if wia.enabled is ever flipped back to true, kept
    # here so this stays correct if that changes.
    wia["wallet_provider_uri"] = config["server"]["base_url"]
    return config


def patch_wallet_backend_fly(config: dict, env: str, extra_android_apk_key_hashes: list = None,
                              mongo_password: str = None, wallet_attestation: bool = False) -> dict:
    # wallet-proxy is wallet-backend's public identity on Fly for the ACTUAL
    # API (see module docstring) - but NOT for WebAuthn. The passkey ceremony
    # (navigator.credentials.create/get) executes in the browser at
    # wallet-frontend's own origin, and WebAuthn requires rp_id to equal (or
    # be a registrable-domain ancestor of) that calling origin - wallet-proxy
    # and wallet-frontend are unrelated sibling *.fly.dev subdomains sharing
    # no such ancestor, so an rp_id of wallet-proxy's domain can never work
    # from a page served at wallet-frontend's domain (confirmed: "passkey
    # creation failed" on every attempt). rp_id/rp_origins must reference
    # wallet-frontend's own domain instead - fly-up.py's WEBAUTHN_RPID env
    # var for the frontend must match this exactly.
    proxy_url = f"https://sirosid-{env}-wallet-proxy.fly.dev"
    frontend_url = f"https://sirosid-{env}-wallet-frontend.fly.dev"
    config["server"]["rp_id"] = f"sirosid-{env}-wallet-frontend.fly.dev"
    android_origins = [o for o in config["server"]["rp_origins"] if o.startswith("android:")]
    # Debug builds / Play Store signing keys the operator wants THIS
    # environment to also authenticate (fly-up.py's --android-app / auto-read
    # .env.android) - these are on top of, not instead of, the production
    # fingerprints siros-id-stack's extraRpOrigins already carries. Registering
    # only in assetlinks.json without also adding the origin here would pass
    # Android's OS-level Digital Asset Links check but still fail the actual
    # WebAuthn ceremony (wallet-backend never accepts the origin).
    for apk_key_hash in extra_android_apk_key_hashes or []:
        origin = f"android:apk-key-hash:{apk_key_hash}"
        if origin not in android_origins:
            android_origins.append(origin)
    config["server"]["rp_origins"] = [frontend_url] + android_origins
    config["server"]["base_url"] = proxy_url
    config["server"]["cors"]["allowed_origins"] = [frontend_url]
    # Unlike local dev (where frontend/backend share an origin via nginx path
    # routing, so the browser never sees a cross-origin request at all), Fly
    # puts wallet-frontend and wallet-backend on genuinely different
    # subdomains - every browser XHR from wallet-frontend is credentialed
    # (withCredentials: true) and cross-origin, so AllowCredentials must be
    # true or the browser rejects the CORS preflight outright (confirmed:
    # every passkey register/login request failed client-side with
    # "Access-Control-Allow-Credentials ... must be 'true'" before this was
    # set - this was never exercised by real-browser testing against a Fly
    # deployment before). Safe only because allowed_origins above is a
    # specific origin, never "*".
    config["server"]["cors"]["allow_credentials"] = True
    config["trust"]["pdp_url"] = f"http://sirosid-{env}-pdp.internal:8080"
    config["trust"]["registry_url"] = f"{proxy_url}/registry"
    # Authenticated - mongodb's own root user/password (fly-up.py generates
    # one per deploy and sets it via Fly secret + MONGO_INITDB_ROOT_* env
    # vars). Any app in the sirosfoundation org could otherwise reach this
    # database over Fly's shared 6PN network with zero credentials.
    if not mongo_password:
        print(
            f"WARNING: --mongo-password not set - rendering an UNAUTHENTICATED "
            f"mongodb URI for env '{env}'. This will not match the mongodb app's "
            f"actual Fly secret (set per-invocation by fly-up.py) unless this "
            f"render happens to run inside that same fly-up.py invocation. "
            f"Re-run 'make fly-up ENV={env}' instead of hand-rendering a single "
            f"component if you're not sure.",
            file=sys.stderr,
        )
    mongo_auth = f"root:{mongo_password}@" if mongo_password else ""
    config["storage"]["mongodb"] = {
        "uri": f"mongodb://{mongo_auth}sirosid-{env}-mongodb.internal:27017/wallet-backend?authSource=admin",
        "tls_enabled": False,
        "database": "wallet-backend",
    }
    # The chart renders cert-manager Secret-volume paths (/wallet-provider-cert/*)
    # for a real Kubernetes deployment; fly-up.py's wallet-backend deploy_args
    # instead lands the private key as a Fly secret and the public cert/CA as
    # --file-local files at these paths (see the `name == "wallet-backend"`
    # branch in deploy_component()).
    # siros-id-stack's wallet-backend template doesn't render a
    # `wallet_provider` block at all today (see CLAUDE.md's wallet_provider.wia
    # gotcha) - setdefault() so this still patches cleanly once it does,
    # without requiring a chart change first.
    wallet_provider = config.setdefault("wallet_provider", {})
    wallet_provider["private_key_path"] = "/main-secrets/walletProviderKey"
    wallet_provider["certificate_path"] = "/main-config/walletProviderCert.pem"
    wallet_provider["ca_cert_path"] = "/main-config/walletProviderCA.pem"
    # go-wallet-backend's own defaultConfig() (pkg/config/config.go) - not the
    # chart, not this script - defaults wia.enabled to true and wia.mode to
    # "etsi" with no wallet_version default, so an absent/empty `wia` block
    # still fails Validate()'s "wallet_version is required" check at startup
    # unless wallet_attestation flips mode to "ietf" below (which has no
    # wallet_version requirement) - explicit either way, matching
    # docker-compose.test.yml's WALLET_WALLET_PROVIDER_WIA_ENABLED precedent
    # rather than relying on the Go default.
    wia = wallet_provider.setdefault("wia", {})
    wia["enabled"] = wallet_attestation
    # WIA-PoP aud claim validation (go-wallet-backend#221): must match
    # whatever URL the wallet SDK treats as "the backend" - on Fly that's
    # proxy_url (server.base_url above), not wallet-backend's own
    # .internal-only hostname. Startup fails hard without this once
    # wia.enabled is true with signing keys configured (pkg/config/config.go's
    # validation).
    wia["wallet_provider_uri"] = config["server"]["base_url"]
    # Opt-in: authenticate to issuers via OAuth-Client-Attestation (the WIA
    # itself) instead of a pre-registered client_id - see
    # build_fly_values_overlay()'s wallet-providers whitelist entry, which
    # this pairs with. Requires an iss claim (below) rather than TS03's
    # x5c-derived identity: go-trust's whitelist registry only resolves
    # trust via JWKS-URL fetch (issuer/verifier/subject entries), it has no
    # custom-CA-pinning mechanism for a self-signed x5c chain, so x5c-based
    # identity can never actually resolve against this environment's PDP.
    # AS.ExternalURL builds the JWKS URL go-tokenauth fetches to verify
    # AS-issued access tokens (used by both HTTP resource endpoints and
    # the WebSocket engine's handshake auth) - left unset, it's "" and
    # the constructed URL is just the bare path "/auth/.well-known/jwks.json",
    # which can never resolve, so every AS-issued token (anonymous or
    # authenticated) fails signature verification with "Invalid or
    # expired token". Confirmed live: WS handshake rejected a token
    # /auth/token had just issued as 200 OK, for every retry. Unconditional -
    # this isn't specific to wallet_attestation, every Fly deployment using
    # the AS/token-based auth path needs it (was previously gated behind
    # `if wallet_attestation:`, which just meant every non-attestation
    # environment silently had broken WS auth).
    config.setdefault("as", {})["external_url"] = proxy_url
    # go-wallet-backend's own hardcoded fallback (ASConfig.SetDefaults,
    # used only when this is unset) is "rwl" - stale relative to what
    # wallet-frontend's real 'backend' token manifest requests
    # (AuthTokens.ts: tac "rwlid", i.e. read/write/list/insert/delete).
    # Every other real deployment already overrides this - both
    # docker-compose.test.yml and docker-compose.helm-config.yml set
    # WALLET_AS_DEFAULT_MAX_TAC=rwlidk (also including 'k'/delegate) -
    # this Fly path is the only one that never carried the same value
    # over, so passkey sessions here got MaxTAC=rwl and every real
    # token request 403ed with "requested permissions exceed session
    # maximum" the moment SPOCP/topology fixes let it get this far.
    config["as"]["default_max_tac"] = "rwlidk"
    # rules_dir is deliberately left unset here, unlike external_url/
    # default_max_tac above: go-wallet-backend's EnableForRole()
    # (pkg/config/config.go) treats an unconfigured RulesDir as "use the
    # baseline policy baked into the image" (rules/default.rules +
    # rules/delegation.rules, COPY'd to /app/rules by the Dockerfile) rather
    # than requiring every deployment to carry its own copy. That baseline
    # already covers this environment's real clients: it wildcards acr (so
    # passkey- and OIDC-authenticated sessions are treated the same) and its
    # one enumerated constraint - anonymous/identity-free tokens capped to
    # aud in {wallet-backend, wallet-registry} - matches exactly the two
    # audiences wallet-frontend's and both native SDKs' AuthTokens clients
    # request. docker-compose.test.yml/docker-compose.helm-config.yml
    # instead point WALLET_AS_RULES_DIR at fixtures/as-rules/allow-all.rules
    # (an unconditional allow, for local/e2e convenience) - Fly relies on
    # the built-in default instead, not an oversight.
    if wallet_attestation:
        wia["issuer"] = config["server"]["base_url"]
        # go-wallet-backend v0.10.0 replaced the old "always include x5c,
        # optionally also include iss" dual-flag design (the field this
        # replaced, `omit_x5c`, isn't even referenced anywhere in current
        # go-wallet-backend Go code - a silently-ignored dead YAML key) with
        # a single mutually-exclusive wia.mode switch: "etsi" (default, no
        # iss, x5c-only identity per TS03 v1.5) vs "ietf" (iss+kid-based,
        # no x5c, draft-ietf-oauth-attestation-based-client-auth). Setting
        # only `issuer` without also flipping `mode` to "ietf" silently fell
        # back to "etsi" - the WIA still carried x5c but the iss claim this
        # environment is supposed to have went missing entirely. Confirmed
        # via a live geneva2026.mdoc.online conformance report: the resulting
        # empty iss is suspected to be why the issuer's credential endpoint
        # started rejecting c_nonce values its own nonce endpoint had just
        # issued (see project_geneva2026_issuer_bugs memory finding #4) -
        # this environment's WIA no longer matched the iss+kid identity
        # shape it worked correctly with before this go-wallet-backend bump.
        wia["mode"] = "ietf"
    return config


def build_fly_values_overlay(env: str, conformance: bool = False,
                              extra_trusted_issuers: list = None,
                              wallet_attestation: bool = False,
                              extra_trusted_verifiers: list = None,
                              extra_trusted_verifier_roots: list = None,
                              rical_provider_url: str = None,
                              rical_root_certificate_pem: str = None) -> dict:
    """Per-env values that can't live in the static values-fly.yaml because they
    embed the env name (hostnames, whitelist entries) - layered on top of it as
    an extra -f file. Mirrors values-dev.yaml's `pdp:` block, just parameterized.
    """
    # The whitelist must match whatever identity string actually appears as
    # the `iss` claim on issued credentials/tokens - that's vc-apigw's PUBLIC
    # url (the rendered config sets both apigw.public_url and
    # issuer.issuer_url/jwt_attribute.issuer to it; vc-issuer's own hostname
    # is never presented as a credential issuer identity, wallets never reach
    # it directly - confirmed by go-trust logging a 404 fetching JWKS from
    # vc-issuer directly, since it isn't meant to be independently
    # discoverable). Real public https:// URLs, so unlike the docker-compose
    # target's local http-only whitelist, JWKS fetch works over real TLS here
    # without needing allow_http for these two entries.
    apigw_url = f"https://sirosid-{env}-vc-apigw.fly.dev"
    verifier_url = f"https://sirosid-{env}-vc-verifier.fly.dev"

    pid_issuers = [apigw_url]
    verifiers = [apigw_url, verifier_url]
    if conformance:
        # go-wallet-backend calls PDP for issuer trust at credential-offer
        # ACCEPTANCE time (internal/engine/oid4vci.go's evaluateTrust, keyed
        # on the offer's credential_issuer URL) - a separate, later check
        # from admin issuer registration, which grants no trust by itself.
        # Without this, every OID4VCI conformance module fails with
        # "untrusted issuer" the moment the wallet tries to accept the
        # suite's own offer, even though it was registered via
        # POST /admin/tenants/:id/issuers. The suite mints a fresh path per
        # test plan (https://.../test/a/<alias>/, alias varies), so a single
        # fixed URL can't cover it - go-trust's whitelist supports a
        # trailing-`*` prefix match (see pkg/registry/static/whitelist.go's
        # matchesList), which does. Added to both lists since the suite acts
        # as issuer (OID4VCI) and verifier (OID4VP) from the same domain,
        # and both spec suites already exist in sirosid-tests.
        conformance_prefix = f"https://sirosid-{env}-conformance.fly.dev/*"
        pid_issuers.append(conformance_prefix)
        verifiers.append(conformance_prefix)

    # Ad-hoc external issuers for interop testing (e.g. a third-party mdoc
    # issuer at a conference/plugfest) - trusted as issuers only, not
    # verifiers, since there's no equivalent need to accept presentation
    # requests from them.
    #
    # These MUST also land in pid_issuers (the whitelist registry), not only
    # mdociaca.issuer_allowlist: go-wallet-backend's offer-acceptance-time
    # issuer check (evaluateTrust -> AuthZEN "credential-issuer" action) is a
    # *resolution-only* request (no key material yet), and go-trust's
    # RegistryManager.getApplicableRegistriesWithPolicy() only queries
    # registries where SupportsResolutionOnly() is true - mdociaca.Registry
    # explicitly returns false there ("requires X5C chains"), so mdociaca is
    # never even consulted for this check, whitelist-membership or not.
    # Confirmed by a live PDP log: "Strategy[FirstMatch]: evaluating
    # registry" only ever listed "... Fly whitelist", never mdociaca, for
    # this action - mdociaca only matters for the LATER, key-bearing check at
    # actual credential-response signature/cert-chain verification time.
    #
    # The whitelist registry's own Evaluate() only needs `r.resolvedLists`
    # (a plain config string/pattern match) for a resolution-only request -
    # it never touches `r.keyHashes` (the fetched-JWKS map) at all in that
    # path - so membership alone is enough; a working JWKS endpoint for the
    # entity is NOT required for this to pass. The cost of pid_issuers
    # membership is purely go-trust's own missing-timeout bug: its initial,
    # synchronous Refresh(context.Background()) at boot (StartRefreshLoop,
    # called before cmd/gt's r.Run() starts the HTTP listener) will spend
    # several minutes failing to fetch JWKS for an issuer with no such
    # endpoint before giving up and continuing - slow (and compounding with
    # vc-apigw/vc-verifier's own pre-existing slow-JWKS-timeout issue, see
    # project_pdp_mdoc_issuer_whitelist_hang memory) but not fatal: the
    # registry keeps working via resolution-only checks regardless of
    # whether the fetch ever succeeds.
    if extra_trusted_issuers:
        pid_issuers.extend(extra_trusted_issuers)

    # Ad-hoc external verifiers for interop testing (e.g. a third-party DC
    # API/mdoc conformance site) - trusted as verifiers only, mirroring
    # extra_trusted_issuers above. Unlike issuers, there's no
    # resolution-only path here: DC API/OpenID4VP trust evaluation for a
    # verifier is a key-bearing check (the presented client_id is
    # cryptographically bound, e.g. x509_hash:<sha256-of-cert>), so an entry
    # here must be whatever literal string go-trust's WhitelistRegistry
    # actually compares against *after* its own Subject.ID normalization -
    # confirmed via a live PDP rejection log that x509_hash:... values are
    # used un-normalized (safe to paste verbatim from the wallet's own error
    # message), while x509_san_dns:<host>/x509_san_uri:<uri> values get
    # normalized to https://<host>/<uri> before any whitelist match runs -
    # an entry written in the original x509_san_dns:/x509_san_uri: form will
    # never match and silently behaves as "not trusted" with no error
    # indicating why.
    if extra_trusted_verifiers:
        verifiers.extend(extra_trusted_verifiers)

    # PEM-encoded CA certs to merge into go-trust's system CA pool
    # (go-trust#123, additional_trusted_roots) for verifiers whose
    # request-signing certificate is issued by a long-lived, self-signed
    # "reader CA" root meant to be trusted out-of-band per ISO 18013-5
    # convention, rather than a public CA - confirmed live for
    # verifier.multipaz.org, whose signing cert (distinct from its ordinary
    # publicly-CA-issued HTTPS cert) is issued by exactly such a root
    # (published at https://verifier.multipaz.org/verifier/readerRootCert).
    # Preferred over x509_hash-pinning the leaf since the root outlives leaf
    # rotations - see go-trust's AdditionalTrustedRoots doc comment.
    extra_trusted_verifier_roots = extra_trusted_verifier_roots or []

    # This environment's own wallet-backend, trusted as a wallet_provider
    # (go-trust's RoleWalletProvider) so SUNET/vc's WalletAttestationEvaluator
    # can authenticate wallets via their WIA alone - no pre-registered
    # client_id (see patch_wallet_backend_fly's wia.issuer/omit_x5c and
    # the apigw's own trust.wallet_attestation). Only added
    # when wallet_attestation is requested, since it's new/unvalidated and
    # every other environment should keep today's behavior unchanged.
    wallet_providers = []
    if wallet_attestation:
        wallet_providers.append(f"https://sirosid-{env}-wallet-proxy.fly.dev")

    lists = {
        "pid-issuers": pid_issuers,
        "verifiers": verifiers,
    }
    actions = {
        "pid-provider": "pid-issuers",
        "credential-issuer": "pid-issuers",
        "verifier": "verifiers",
        "credential-verifier": "verifiers",
    }
    if wallet_providers:
        lists["wallet-providers"] = wallet_providers
        actions["wallet_provider"] = "wallet-providers"

    whitelist_config = {
        "enabled": True,
        "name": f"sirosid-{env} Fly whitelist",
        "description": "Fly-hosted vc-services URLs (rendered from siros-id-stack schema)",
        "lists": lists,
        "actions": actions,
        # Required for extra_trusted_verifiers entries identified by a
        # non-fetchable client_id scheme (x509_hash:.../x509_san_dns:...)
        # rather than a JWKS URL - go-trust's WhitelistRegistry denies
        # with "no keys cached for entity" for such an entity unless
        # this is set, even when whitelist membership matches (see
        # pkg/registry/static/whitelist.go's TrustX509ViaSystemCA doc
        # comment). Still gated by the whitelist-membership check
        # itself, so this is safe to enable unconditionally rather
        # than only when extra_trusted_verifiers is non-empty -
        # confirmed live: silently omitting this field (as this
        # function did before) is indistinguishable from a whitelist
        # rejection in the wallet's own error message, and cost real
        # debugging time tracing through go-trust's source to find.
        "trust_x509_via_system_ca": True,
    }
    if extra_trusted_verifier_roots:
        whitelist_config["additional_trusted_roots"] = extra_trusted_verifier_roots

    extra_registries = {
        "whitelist": whitelist_config,
        # The whitelist registry above only ever caches JWT-signing
        # keys (via jwt-vc-issuer/jwks_uri discovery) - it has no
        # notion of an issuer's mdoc_iacas_uri. An mdoc issuer's
        # extractIssuerKeyMaterial (go-wallet-backend) prioritizes
        # mdoc_iacas_uri over JWKS, so any issuer offering mso_mdoc
        # credentials needs this separate registry too, or trust
        # evaluation permanently denies with "no keys cached for
        # entity" regardless of whitelist membership. Reuses the same
        # pid_issuers list as the trust boundary (not "trust any
        # issuer that publishes a valid IACA").
        "mdociaca": {
            "enabled": True,
            "name": f"sirosid-{env} mDOC IACA registry",
            "description": "IACA cert validation for mso_mdoc issuers (rendered from siros-id-stack schema)",
            "issuer_allowlist": pid_issuers,
        },
    }

    # RICAL (ISO 18013-5 2nd ed. Annex F) reader-trust: a separate registry
    # from the whitelist above, since it path-validates a reader's x5c
    # chain against a centrally-published, COSE_Sign1-signed trust-anchor
    # list rather than checking URL membership. go-trust's mdocrical
    # registry self-declares its own supported resource type ("x5c") and
    # needs no entry in whitelist_config["actions"] - it's asked for every
    # "mdoc-reader-auth" evaluation once registered, same as mdociaca is
    # asked for every mso_mdoc issuer check without an actions-map entry.
    if rical_provider_url and rical_root_certificate_pem:
        extra_registries["mdocrical"] = {
            "enabled": True,
            "name": f"sirosid-{env} RICAL registry",
            "description": "Reader-trust list for mdoc BLE/NFC proximity presentation (rendered from siros-id-stack schema)",
            "rical_provider_url": rical_provider_url,
            "rical_root_certificate_pem": rical_root_certificate_pem,
        }

    frontend_url = f"https://sirosid-{env}-wallet-frontend.fly.dev"
    overlay = {
        "tenant": {"id": env},
        # Every vc service's public identity. These are load-bearing beyond
        # addressing: the verifier's OpenID4VP client_id is derived from its
        # public_url ("x509_san_dns:<host>"), and the apigw's public URL is
        # the credential-issuer identity that appears as the `iss` claim - so
        # these must be the same strings the PDP whitelist above names.
        # issuer-core is deliberately absent: it is an internal gRPC signing
        # service that advertises the apigw's URL, never its own.
        "hostnames": {
            "issuer": f"sirosid-{env}-vc-apigw.fly.dev",
            "issuerRegistry": f"sirosid-{env}-vc-registry.fly.dev",
            "verifier": f"sirosid-{env}-vc-verifier.fly.dev",
            "walletFrontend": f"sirosid-{env}-wallet-frontend.fly.dev",
            "walletBackend": f"sirosid-{env}-wallet-proxy.fly.dev",
        },
        # fly-up.py deploys wallet-frontend with a hardcoded
        # BASE_PATH=/id/default/ (_wallet_frontend_env()), and
        # register_vc_services() registers the "default" tenant - so the base
        # path does NOT follow tenant.id, which is the environment name here.
        # Every redirect_uri the chart derives has to agree with the path the
        # SPA router actually serves, or the OID4VCI/OID4VP callback lands on
        # a blank page (nginx serves the shell, the router mounts nothing).
        "walletFrontend": {"basePath": "/id/default"},
        "issuer": {
            "authProviders": {"oidc": {
                "issuerUrl": f"https://sirosid-{env}-mini-oidc.fly.dev",
                "clientId": fly_common.MINI_OIDC_APIGW_CLIENT_ID,
            }},
            "apigw": {"extraConfig": {"apigw": {
                # gRPC over Fly's 6PN, not the public edge.
                # tls: false - the chart wires cert-manager mTLS between k8s
                # Services; Fly's 6PN is already a private per-environment
                # network and there are no such certs here.
                "issuer_client": {"addr": f"sirosid-{env}-vc-issuer.internal:8090", "tls": False},
                "registry_client": {"addr": f"sirosid-{env}-vc-registry.internal:8090", "tls": False},
                "delivery": {"openid4vci": {"clients": {
                    # Restated in full, not appended: a list in extraConfig
                    # replaces. This is the client_id fly-up.py's
                    # register_vc_services() registers with wallet-backend as
                    # THE one used for OID4VCI authorization_code flows, web
                    # and native alike, so it needs both the native deep link
                    # and this environment's own frontend callback - dropping
                    # either 401s that platform with invalid_client.
                    "e2e-test-client": {
                        "type": "public",
                        "redirect_uri": [
                            "siros-sample://callback",
                            "http://localhost:3000/id/default/cb",
                            f"{frontend_url}/id/default/cb",
                        ],
                        "scopes": ["pid", "pid_1_5", "pid_1_8", "diploma", "ehic",
                                   "mdl", "mdl_zk4", "pid_mdoc"],
                    },
                }},
                "credential_offers": {"wallets": {
                    # Standard OpenID4VCI same-device scheme, registered by
                    # both native sample apps, so a native wallet can be handed
                    # an offer directly from the /offers chooser.
                    "local": {"redirect_uri": f"{frontend_url}/id/default/cb"},
                }}},
            }}},
            "core": {"extraConfig": {"issuer": {
                "registry_client": {"addr": f"sirosid-{env}-vc-registry.internal:8090", "tls": False},
            }}},
        },
        "pdp": {
            "default_whitelist": False,
            "externalUrl": f"http://sirosid-{env}-pdp.internal:8080",
            "extraRegistries": extra_registries,
        },
    }
    if wallet_attestation:
        # Let wallets authenticate with their WIA alone rather than a
        # pre-registered client_id, delegating the trust decision to the PDP -
        # pairs with the wallet-providers whitelist entry above.
        overlay["issuer"]["apigw"]["walletAttestation"] = {"enabled": True}
        overlay.setdefault("verifier", {})["walletAttestation"] = {"enabled": True}
    return overlay


def build_toggles_overlay(zk_circuits_sources: list = None, dc_api_enable: str = "") -> dict:
    """The per-run verifier toggles that mean the same thing on both targets.

    Kept out of build_fly_values_overlay so `make up DC_API=yes` and
    `make fly-up ENV=x DC_API_ENABLE=true` reach the identical value, rather
    than one of them silently doing nothing - which is what happened before,
    when DC_API was a compose-only flag patched by one script
    and DC_API_ENABLE a separate Fly-only one patched by patch-vc-config-fly.py.
    """
    verifier = {}
    if zk_circuits_sources:
        # vc defaults to https://zk-circuits.fly.dev; an environment testing a
        # circuit not published there yet points at its own mirror.
        verifier["zkCircuits"] = {"sources": zk_circuits_sources}
    if dc_api_enable:
        verifier["digitalCredentials"] = {"enabled": dc_api_enable == "true"}
    return {"verifier": verifier} if verifier else {}


def render(target: str, chart_dir: Path, env: str = None, android_apk_key_hashes: list = None,
           namespace: str = "sirosid-dev", out_dir: Path = None, secrets_dir: Path = None,
           mongo_password: str = None, conformance: bool = False,
           extra_trusted_issuers: list = None, wallet_attestation: bool = False,
           extra_trusted_verifiers: list = None, extra_trusted_verifier_roots: list = None,
           rical_provider_url: str = None, rical_root_certificate_pem: str = None,
           zk_circuits_sources: list = None, dc_api_enable: str = "",
           hostnames: dict = None, mini_oidc_url: str = "",
           env_values: dict = None) -> list:
    """Does the actual `helm template` + extract + patch + write-files work for
    one target; returns the rendered manifest's docs so a caller that also
    needs OTHER parts of the same manifest (fly-up.py: image refs, mongo
    version, wallet-frontend's Android/iOS wellknown values) can reuse this
    one render instead of invoking `helm template` a second time.
    """
    if target == "fly" and not env:
        raise ValueError("target 'fly' requires env")

    out_dir = Path(out_dir) if out_dir else SIROSID_DEV_ROOT / "fixtures" / "rendered"
    if target == "fly":
        out_dir = out_dir / f"fly-{env}"
    out_dir.mkdir(parents=True, exist_ok=True)

    # Values layering, later wins (helm deep-merges each -f in order):
    #   the chart's own values.yaml (applied automatically)
    #   values-base.yaml       what sirosid-dev issues and verifies, both targets
    #   values-dev/fly.yaml    target-specific
    #   values.generated.yaml  per-run: hostnames, whitelist, mongo password
    #   environments/<env>.yaml's `values:` block, merged last
    #
    # values-base.yaml is preprocessed rather than passed straight through:
    # it references VCTM/MDDL/bootstrapping documents by repo-relative path,
    # and helm's Files.Get cannot read outside the chart directory, so those
    # are inlined as `data` first (see vc_render.inline_file_refs).
    check_chart_supported(Path(chart_dir))

    base = yaml.safe_load((SIROSID_DEV_ROOT / "values-base.yaml").read_text())
    vc_render.inline_file_refs(base)
    vc_render.expand_presentation_request_templates(base)
    base_path = out_dir / "values.base-inlined.yaml"
    base_path.write_text(yaml.dump(base, sort_keys=False))

    values_files = [base_path]
    if target == "compose":
        values_files.append(SIROSID_DEV_ROOT / "values-dev.yaml")
    else:
        values_files.append(SIROSID_DEV_ROOT / "values-fly.yaml")
        overlay_path = out_dir / "values.generated.yaml"
        overlay_path.write_text(yaml.dump(
            build_fly_values_overlay(env, conformance, extra_trusted_issuers, wallet_attestation,
                                      extra_trusted_verifiers, extra_trusted_verifier_roots,
                                      rical_provider_url, rical_root_certificate_pem), sort_keys=False))
        values_files.append(overlay_path)

    # Hostname overrides for a run that isn't reachable at the target's usual
    # addresses - TUNNELS=yes (real-TLS Cloudflare quick tunnels) and Android
    # testing (the emulator reaches mini-oidc on its own bridge address). These
    # used to be three separate pre-patched copies of the vc config.
    host_overlay = {}
    if hostnames:
        host_overlay["hostnames"] = dict(hostnames)
    if mini_oidc_url:
        host_overlay.setdefault("issuer", {}).setdefault("authProviders", {})["oidc"] = {
            "issuerUrl": mini_oidc_url}
    if host_overlay:
        host_path = out_dir / "values.hostnames.yaml"
        host_path.write_text(yaml.dump(host_overlay, sort_keys=False))
        values_files.append(host_path)

    toggles = build_toggles_overlay(zk_circuits_sources, dc_api_enable)
    if toggles:
        toggles_path = out_dir / "values.toggles.yaml"
        toggles_path.write_text(yaml.dump(toggles, sort_keys=False))
        values_files.append(toggles_path)

    # A named environment's own `values:` block goes last, so it can override
    # anything above it - see scripts/env_config.py. Applies to both targets:
    # `make up ENV=<name>` and `make fly-up ENV=<name>` layer the same file.
    if env_values:
        env_values_path = out_dir / "values.environment.yaml"
        env_values_path.write_text(yaml.dump(env_values, sort_keys=False))
        values_files.append(env_values_path)

    manifest = helm_template(chart_dir, values_files, namespace if target == "compose" else f"sirosid-{env}")
    docs = load_manifest_docs(manifest)

    # --- wallet-backend ---
    wb_data = extract_configmap_data(docs, "wallet-backend-main")
    backend_cfg = yaml.safe_load(wb_data["backend.yaml"])
    if target == "compose":
        backend_cfg = patch_wallet_backend_compose(backend_cfg, android_apk_key_hashes)
    else:
        backend_cfg = patch_wallet_backend_fly(backend_cfg, env, android_apk_key_hashes, mongo_password,
                                                wallet_attestation)
    (out_dir / "wallet-backend.yaml").write_text(yaml.dump(backend_cfg, sort_keys=False))

    registry_cfg = yaml.safe_load(wb_data["registry.yaml"])
    if target == "fly":
        # The chart's /cache mount (templates/04-wallet-backend.yaml) is a
        # real k8s emptyDir, writable via the pod's fsGroup securityContext -
        # but fly-up.py deploys this same rendered config as a plain Fly
        # Machine, not a Kubernetes pod, so fsGroup never applies and /cache
        # is whatever the image provides for uid 65532 (usually nothing
        # writable). Confirmed live: "failed to create cache directory:
        # mkdir /cache: permission denied" on every poll, so the fetcher
        # silently never persists its cache and refetches all VCTMs each
        # cycle. /tmp is conventionally world-writable regardless of image
        # USER, and this cache is a pure performance optimization (refetched
        # from registry.siros.org on miss) - safe to just redirect it there
        # for this target rather than fixing the image or adding a real Fly
        # volume for what's disposable data.
        registry_cfg.setdefault("cache", {})["path"] = "/tmp/vctm-cache.json"
    (out_dir / "wallet-backend-registry.yaml").write_text(yaml.dump(registry_cfg, sort_keys=False))
    print(f"wrote {out_dir / 'wallet-backend.yaml'}")
    print(f"wrote {out_dir / 'wallet-backend-registry.yaml'}")

    # registry.yaml's local_overrides always points at /vctms - Helm mounts this
    # from a `vctms` ConfigMap (created even when empty), so the directory must
    # exist here too or the registry provider fails to start (`stat /vctms: no
    # such file or directory`), even with features.credentialTypes: {}.
    (out_dir / "vctms").mkdir(exist_ok=True)

    # registry.yaml's cache.path lives under /cache, which Helm mounts as an
    # emptyDir (writable by the pod's fsGroup) - true for the compose target's
    # own bind-mounted dir below. go-wallet-backend runs as uid 65532
    # (Dockerfile:45), and a bind-mounted dir defaults to the host user's
    # ownership, so it must be made world-writable here explicitly. Fly's
    # override above replaces this path entirely for that target instead.
    cache_dir = out_dir / "cache"
    cache_dir.mkdir(exist_ok=True)
    cache_dir.chmod(0o777)

    # --- wallet-backend AS rules + signing key ---
    # See vc_render.write_as_rules: the chart's `as:` block names paths that
    # only exist in Kubernetes, and a missing signing key is fatal.
    vc_render.write_as_rules(docs, out_dir)
    print(f"wrote {out_dir / 'as-rules'}/")

    # --- pdp ---
    pdp_data = extract_configmap_data(docs, "pdp-main")
    (out_dir / "pdp.yaml").write_text(pdp_data["config.yaml"])
    print(f"wrote {out_dir / 'pdp.yaml'}")

    # --- vc services (issuer-apigw / issuer-core / issuer-registry / verifier) ---
    # Secrets for these are rendered for BOTH targets, unlike wallet-backend's:
    # the chart's secrets-renderer initContainer doesn't exist outside
    # Kubernetes, and vc reads them from a file named by
    # common.secret_file_path rather than from the environment.
    secrets_dir = Path(secrets_dir) if secrets_dir else SIROSID_DEV_ROOT / "fixtures" / "rendered-secrets"
    vc_render.render_vc(docs, out_dir, target, secrets_dir, gen_secret,
                        plain_http_hosts=vc_render.COMPOSE_PLAIN_HTTP_HOSTS,
                        secret_overrides={
                            # Not ours to generate: it has to be the secret
                            # mini-oidc itself was configured with, which
                            # fly-up.py sets from these same constants and
                            # docker-compose.vc-services.yml defaults to.
                            "OIDC_PROVIDER_CLIENT_SECRET": fly_common.MINI_OIDC_APIGW_CLIENT_SECRET,
                        },
                        env=env, mongo_password=mongo_password)

    if target == "compose":
        # --- secrets (mirrors config/secret_generator_template.yaml's randAlphaNum 32) ---
        for name in WALLET_BACKEND_SECRETS:
            gen_secret(secrets_dir / name)
        print(f"secrets ready in {secrets_dir} ({', '.join(WALLET_BACKEND_SECRETS)})")
    else:
        print("--target fly: wallet-backend secrets are handled by fly-up.py (fly secrets set), not here")

    return docs


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--chart-dir", default=str(SIROSID_DEV_ROOT.parent / "siros-id-stack"),
                         help="Path to the siros-id-stack chart (default: ../siros-id-stack)")
    parser.add_argument("--target", choices=["compose", "fly"], default="compose")
    parser.add_argument("--env", help="Environment name, required for --target fly (e.g. test1)")
    parser.add_argument("--android-apk-key-hash", action="append", default=[],
                         help="base64url apk-key-hash (no padding) to add to wallet-backend's "
                              "rp_origins, on top of the production ones siros-id-stack already "
                              "carries - repeatable, applies to both --target compose and "
                              "--target fly. See scripts/android_apps.py (.android-apps / "
                              "--android-app) for the developer-facing (colon-hex) form of this "
                              "- the Makefile passes its output through here for both targets.")
    parser.add_argument("--mongo-password", default=None,
                         help="--target fly only: mongodb root password (fly-up.py generates and sets "
                              "this as a Fly secret on the mongodb app itself; passed here so "
                              "wallet-backend's config embeds a matching authenticated connection URI). "
                              "Omitting this does NOT error - it silently renders an UNAUTHENTICATED "
                              "mongo URI instead. Only safe within the same fly-up.py invocation that "
                              "set the matching Fly secret; for a one-off render, just re-run "
                              "'make fly-up ENV=<name>' instead.")
    parser.add_argument("--hostname", action="append", default=[], metavar="ROLE=HOST",
                        help="override one chart hostname, e.g. issuer=abc.trycloudflare.com. "
                             "Roles: issuer (the apigw), issuerRegistry, verifier, walletFrontend, "
                             "walletBackend. A host not in vc_render.COMPOSE_PLAIN_HTTP_HOSTS keeps "
                             "the chart's https:// scheme, which is what TUNNELS=yes wants.")
    parser.add_argument("--mini-oidc-url", default="",
                        help="the OIDC provider apigw authenticates users against; overrides "
                             "values-dev.yaml's compose default (Waydroid reaches it on a "
                             "different address than the host does).")
    parser.add_argument("--dc-api-enable", default="",
                        help="'true'/'false' to force the verifier's W3C Digital Credentials API "
                             "support on or off; empty leaves values-base.yaml's own setting. "
                             "Means the same thing on both targets.")
    parser.add_argument("--zk-circuits-source", action="append", default=[],
                        help="zk-circuits catalog mirror base URL, repeatable/comma-separated; "
                             "empty uses vc's own default.")
    parser.add_argument("--env-values", action="store_true",
                        help="also layer environments/<env>.yaml's `values:` block (requires --env)")
    parser.add_argument("--conformance", action="store_true",
                         help="--target fly only: also whitelist the conformance suite's issuer/verifier "
                              "identity (https://sirosid-<env>-conformance.fly.dev/*) with PDP, so the "
                              "wallet accepts credential offers/presentation requests from it during "
                              "OID4VCI/OID4VP conformance testing - see build_fly_values_overlay().")
    parser.add_argument("--namespace", default="sirosid-dev")
    parser.add_argument("--out-dir", default=str(SIROSID_DEV_ROOT / "fixtures" / "rendered"))
    parser.add_argument("--secrets-dir", default=str(SIROSID_DEV_ROOT / "fixtures" / "rendered-secrets"))
    args = parser.parse_args()

    if args.target == "fly" and not args.env:
        parser.error("--target fly requires --env <name>")

    chart_dir = Path(args.chart_dir)
    if not chart_dir.is_dir():
        raise SystemExit(
            f"Chart not found at {chart_dir} - clone sibling repo "
            f"'siros-id-stack' next to sirosid-dev, or pass --chart-dir "
            f"(see SIROS_ID_STACK_PATH in the Makefile)"
        )

    if args.env_values and not args.env:
        parser.error("--env-values requires --env <name>")
    env_values = {}
    if args.env_values:
        import env_config
        env_values = env_config.load_environment_config(args.env).get("values") or {}

    zk_sources = [u.strip() for arg in args.zk_circuits_source for u in arg.split(",") if u.strip()]

    render(args.target, chart_dir, env=args.env, android_apk_key_hashes=args.android_apk_key_hash,
           namespace=args.namespace, out_dir=Path(args.out_dir), secrets_dir=Path(args.secrets_dir),
           mongo_password=args.mongo_password, conformance=args.conformance,
           dc_api_enable=args.dc_api_enable, zk_circuits_sources=zk_sources,
           hostnames=dict(h.split("=", 1) for h in args.hostname),
           mini_oidc_url=args.mini_oidc_url, env_values=env_values)


if __name__ == "__main__":
    main()
